# Import the libraries

In [2]:
#Numpy for numerical computing
import numpy as np

#Pandas for DataFrames
import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt

from sklearn import datasets, linear_model, metrics
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

from numpy.polynomial.polynomial import polyfit
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt

# Load the dataset

In [41]:
#Load Real Estate Data from csv

df = pd.read_csv('C:\\NachuMohan\\Saint_Peters_University\\GA_Summer2020\\Demographic_Limited.csv')

In [42]:
df

,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Under 5 years,Estimate!!SEX AND AGE!!Total population!!5 to 9 years,Estimate!!SEX AND AGE!!Total population!!10 to 14 years,Estimate!!SEX AND AGE!!Total population!!15 to 19 years,Estimate!!SEX AND AGE!!Total population!!20 to 24 years,Estimate!!SEX AND AGE!!Total population!!25 to 34 years,Estimate!!SEX AND AGE!!Total population!!35 to 44 years,Estimate!!SEX AND AGE!!Total population!!45 to 54 years,Estimate!!SEX AND AGE!!Total population!!55 to 59 years,Estimate!!SEX AND AGE!!Total population!!60 to 64 years,Estimate!!SEX AND AGE!!Total population!!65 to 74 years,Estimate!!SEX AND AGE!!Total population!!75 to 84 years,Estimate!!SEX AND AGE!!Total population!!85 years and over,Estimate!!RACE!!Total population,Estimate!!RACE!!Total population!!One race!!White,Estimate!!RACE!!Total population!!One race!!Black or African American,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping,Estimate!!RACE!!Total population!!One race!!Asian,Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian,Estimate!!RACE!!Total population!!One race!!Asian!!Chinese,Estimate!!RACE!!Total population!!One race!!Asian!!Filipino,Estimate!!RACE!!Total population!!One race!!Asian!!Japanese,Estimate!!RACE!!Total population!!One race!!Asian!!Korean,Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese,Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Some other race,Estimate!!RACE!!Total population!!Two or more races,Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American,Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native,Estimate!!RACE!!Total population!!Two or more races!!White and Asian,Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population,Estimate!!Race alone or in combination with one or more other races!!Total population!!White,Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Estimate!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian,Estimate!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander,Estimate!!Race alone or in combination with one or more other races!!Total population!!Some other race,Estimate!!HISPANIC OR LATINO AND RACE!!Total population,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race,"Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Estimate!!Total housing units,"Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female"
0,Illinois,12741080,6266062,6475018,759456,762237,838140,835845,839026,1765517,1644390,1636054,855616,814251,1143329,587651,259568,12741080,9135145,1793079,35846,3055,2651,135,222,717938,256122,132447,124649,17958,56597,35367,94798,5317,1927,789,710,1891,712778,340977,116872,35817,82982,8368,12741080,9431680,1952694,100555,831487,16444,776129,12741080,2208868,1744028,206543,27617,230680,10532212,7760732,1759316,17215,711970,2887,24310,255782,11405,244377,5376176,9074766,4385340,4689426
1,Iowa,3156145,1564888,1591257,197883,197454,215222,220659,220135,394507,383617,369396,213657,205797,299333,162869,75616,3156145,2846099,115137,11494,603,153,264,1964,79971,12415,13121,5029,1494,6717,11705,29490,3463,541,561,348,2013,30713,69268,30402,9285,13266,1951,3156145,2909568,151562,27116,98900,6579,37007,3156145,191473,155179,7792,1714,26788,2964672,2695583,113562,9710,79643,2945,4000,59229,493,58736,1409568,2327219,1139250,1187969
2,Missouri,6126452,3003165,3123287,370408,373737,401199,391923,406398,819132,742343,753354,419591,413293,596623,313646,124805,6126452,5035197,704327,27705,8373,462,1210,653,121417,30435,29621,11302,2388,11526,17208,18937,7385,1844,226,2729,2586,56557,173864,75345,39150,29126,4404,6126452,5196815,794984,79954,159166,13760,66685,6126452,253474,179787,16816,8220,48651,5872978,4857174,698641,23149,120440,7095,9832,156647,2330,154317,2806296,4633370,2240784,2392586
3,Nevada,3034392,1522374,1512018,184539,188880,201625,182398,180376,442713,405128,396167,191059,186387,291996,138844,44280,3034392,1924976,280385,44666,2626,512,2425,857,250137,11123,39196,129739,11514,11750,17744,29071,19612,6472,5668,3528,3944,358786,155830,32463,14754,38991,5393,3034392,2050048,337660,71817,318010,41746,390057,3034392,881145,668365,25740,35071,151969,2153247,1469593,266440,30185,244471,18249,11810,112499,3740,108759,1268717,2075166,1036350,1038816
4,Pennsylvania,12807060,6271620,6535440,700416,708163,775827,815621,812406,1695073,1496113,1659541,916749,894782,1311159,707570,313640,12807060,10256084,1428406,21418,2569,351,302,447,455027,143539,119817,25128,5056,39144,40920,81423,5008,935,746,766,2561,307572,333545,148313,32795,55627,11223,12807060,10543254,1632035,89728,536235,18764,355417,12807060,974763,158286,477312,24185,314980,11832297,9723288,1352804,14367,450077,3557,21357,266847,11356,255491,5713136,9781212,4726343,5054869
5,Utah,3161105,1592457,1568648,250194,257110,270952,250173,260774,463344,437953,319031,152425,147852,212206,103828,35263,3161105,2708195,40365,34678,709,0,15970,2265,75898,12079,14285,8034,6208,6756,9663,18873,29362,2090,836,8386,18050,171456,101151,12469,17190,29698,988,3161105,2800377,58241,56454,115638,47609,191869,3161105,450220,313226,12566,2766,121662,2710885,2459891,37546,27959,74784,28810,6356,75539,2925,72614,1108739,2087341,1041497,1045844
6,West Virginia,1805832,894657,911175,93922,97203,107390,112776,113760,209002,218803,233109,127449,131202,215290,105707,40219,1805832,1679773,68679,2629,N,N,N,N,13459,2331,3893,1994,686,1396,1137,2022,451,N,N,N,N,6430,34411,19582,5340,4574,200,1805832,1712618,89894,9599,19875,2577,8067,1805832,25569,11319,4112,1351,8787,1780263,1661773,68042,2535,13311,451,2286,31865,335,31530,893742,1431158,701390,729768
7,Colorado,5695564,2864761,2830803,335642,352145,364535,368833,374122,889656,781388,710218,362167,349003,502418,218031,87406,5695564,4790677,237578,55146,4602,590,7270,4219,180277,35512,33422,19141,9912,22998,25088,34204,7585,1994,3276,205,2110,196831,227470,51313,51921,54185,2651,5695564,4997140,311745,126983,254210,19880,237478,5695564,1235127,911881,38288,12183,272775,4460437,3859171,223299,31977,177495,6616,10755,151124,5359,145765,2424128,4151040,2073626,2077414
8,Georgia,10519475,5120290,5399185,645488,683042,739018,754377,719378,1442243,1401044,1396330,667863,614264,896948,416680,142800,10519475,6127645,3319691,34485,5950,727,502,347,436051,141915,68404,26109,9166,53227,60114,77116,14049,2435,5022,705,5887,301148,286406,115366,29089,47451,11143,10519475,6365137,3487272,92014,509357,26155,348034,10519475,1021754,593262,103647,35052,289793,9497721,5493804,3281137,17359,431551,11618,33630,228622,7548,221074,4326266,7486799,3558929,3927870
9,Idaho,1754208,882158,872050,113693,123959,129947,127012,115850,228080,219713,201135,111993,103385,168397,81341,29703,1754208,1576846,12075,23026,894,218,974,426,27026,2942,5862,6703,2918,895,3349,4357,2763,1432,791,268,272,59217,53255,6899,14200,11981,243,1754208,1626499,22173,41448,45610,7162,71096,1754208,222464,188003,7281,1015,26165,1531744,1434463,10007,18867,26186,2222,1429,38570,486,38084,735703,1252414,622965,629449
10,Maryland,6042718,2930350,3112368,361435,364571,385477,379728,384168,826526,775079,822740,418074,393879,546442,276084,108515,6042718,3305047,1810885,13433,1091,101,17,436,378985,99035,89525,49140,6545,45273,28104,61363,7311,N,N,N,N,304042,223015,73892,20984,51972,8612,6042718,3489566,1932303,60221,459537,15994,335682,6042718,628435,108960,60552,13050,445873,5414283,3035148,1782090,9701,376805,2263,25852,182424,10479,171945,2458779,4320150,2055984,2264166
11,New Jersey,8908520,4350386,4558134,517694,517905,573092,556312,554274,1151093,1147591,1233599,634688,583983,812353,430178,195758,8908520,5956539,1207995,21131,N,N,N,N,868213,387244,153447,120222,12448,99165,19085,76602,2909,N,N,N,N,604334,247399,82074,12437,57486,7193,8908520,6154690,1335579,56649,956049,11641,664813,8908520,1839359,211254,488181,97336,1042588,7069161,4864534,1137645,8921,861223,1777,40261,154800,15034,139766,3628198,6198334,2977776,3220558
12,New Mexico,2095428,1039641,1055787,118494,127795,151078,142717,138863,279153,256261,239928,136486,136173,221209,106536,40735,2095428,1599938,46064,200659,798,806,124715,622,34155,6608,6222,7927,1518,2490,5779,3611,2465,N,N,N,N,144961,67186,9812,18430,9131,908,2095428,1658939,61079,226911,47195,4997,168030,2095428,1029229,641955,9606,4240,373428,1066199,773039,39940,183944,31807,2030,3662,31777,2491,29286,943232,1507384,735509,771875
13,Ohio,11689442,5732095,5957347,693129,691126,752239,773272,752641,1533104,1396763,1488201,816288,796516,1152361,595517,248285,11689442,9470940,1446306,25672,6858,622,312,932,271762,95049,59617,18275,11629,17893,17619,51680,4228,828,287,538,2575,112136,358398,182751,47213,51975,13585,11689442,9794421,1674699,104484,345724,13486,141318,11689442,455918,206307,137104,11362,101145,11233524,9182383,1425930,18605,269314,3819,20784,312689,7814,304875,5217617,8863920,4282540,4581380
14,Alaska,737438,382952,354486,52173,52544,49747,48514,49107,117688,97020,89333,47300,46012,59630,21000,7370,737438,474555,25197,111371,752,962,38,797,46381,1376,2988,28497,749,3484,810,8477,7958,383,1163,4639,1773,9780,62196,5434,29350,8997,2161,737438,529846,36659,149430,63855,14092,13875,737438,53069,28656,8156,1870,14387,684369,443304,24011,107887,45513,7877,895,54882,863,54019,318352,532244,279792,252452
15,Florida,21299325,10404676,10894649,1135392,1127602,1244592,1234024,1255590,2758515,2586704,2741968,1449290,1406864,2404234,1393550,561000,21299325,15899574,3410741,59870,10006,1459,1277,560,593634,171778,112990,107199,17542,30485,72431,81209,12841,2772,4389,1653,4027,708740,613925,231541,68105,109703,15073,21299325,16428821,3731939,171405,774567,43479,818951,21299325,5562452,736566,1187437,1580886,2057563,15736873,11344261,3252558,41492,580229,9694,81784,426855,23138,403717,9547762,15327815,7371100,7956715
16,Hawaii,1420491,710702,709789,87437,84434,84576,77860,90595,201025,181541,171390,86295,93871,149372,72022,40073,1420491,345652,28325,3237,865,0,135,123,534479,2249,56584,220315,163174,24804,12213,55140,144971,91442,4363,11237,37929,18052,345775,5159,8601,71631,1038,1420491,600675,53844,30383,807332,383172,45189,1420491,151356,46165,45801,2362,57028,1269135,308375,26978,1976,521237,134876,1321,274372,1266,273106,546261,1016506,513093,503413
17,Massachusetts,6902149,3350887,3551262,357223,369278,392598,457341,492981,990332,842140,921551,490589,450575,656546,327266,153729,6902149,5335175,537523,16198,N,N,N,N,472403,120063,179716,15409,8933,23561,52771,71950,2775,647,1126,489,513,303331,234744,95685,18960,52189,5855,6902149,5538925,666025,52093,540441,8234,348753,6902149,846780,51415,329713,14621,451031,6055369,4882418,483673,10754,468665,2185,53791,153883,18373,135510,2915043,5035804,2400775,2635029
18,South Carolina,5084127,2468707,2615420,287356,307540,323598,340480,332798,654355,623363,637009,349353,328521,553062,261920,84772,5084127,3407706,1353599,23672,N,N,N,N,80969,21145,15787,13260,3393,4741,13641,9002,4004,910,961,271,1862,92980,121197,50580,17005,17042,7602,5084127,3511420,1423790,53066,107491,9865,111572,5084127,294502,147935,40888,9358,96321,4789625,3229793,1345077,16553,80638,3685,11601,102278,4395,97883,2318291,3850077,1830316,2019761
19,District of Columbia,702455,334208,368247,45490,32857,33386,37568,52978,163467,105535,75526,36869,33153,48833,25892,10901,702455,296747,319777,1932,N,N,N,N,27538,6317,8516,3006,1670,3273,1628,3128,397,N,N,N,N,30897,25167,6672,1054,7586,1967,702455,315977,333496,6722,38036,1160,35616,702455,79249,12161,6146,4776,56166,623206,259371,311654,1281,26959,336,3502,20103,1424,18679,319579,526393,245922,280471
20,Maine,1338404,655734,682670,63410,67860,72549,77325,73878,159944,153436,180466,105214,108253,163953,77267,34849,1338404,1261453,18954,8566,N,N,N,N,15683,2629,3305,2544,1259,1811,1930,2205,465,N,N,N,N,3264,30019,6727,11857,5967,367,1338404,1289950,27637,22607,23286,1880,5459,1338404,22411,7270,6248,2234,6659,1315993,1245001,18501,8204,15356,89,1315,27527,461,27066,746592,1070661,518367,552294
21,North Carolina,10383620,5052244,5331376,597192,620626,679947,701383,682328,1382310,1310404,1378087,677844,664925,1013996,495511,179067,10383620,7098569,2222533,120845,14768,813,613,450,306682,104438,53510,20713,8752,22544,28006,68719,10218,1416,4255,1218,3329,326630,298143,113981,44768,44443,20927,10383620,7347405,2398801,205652,376535,24349,358550,10383620,995529,564685,110248,27695,292901,9388091,6505973,2184448,108795,303651,8539,25927,250758,10100,240658,4684962,7629700,3634888,3994812
22,South Dakota,882235,445271,436964,60427,58765,61566,59836,58791,116300,105167,97263,58813,58949,85022,39575,21761,882235,740870,19057,78068,54,819,259,57592,15023,3533,1107,1473,250,763,930,6967,51,N,N,N,N,5782,23384,5901,11790,2148,574,882235,763432,26781,92049,17534,819,6550,882235,33983,19762,2853,159,11209,848252,718783,18895,74907,14791,51,271,20554,3,20551,397506,647089,323519,323570
23,Alabama,4887871,2369271,2518600,288589,290369,321430,332209,317810,635976,593480,626173,332700,319472,493396,251025,85242,4887871,3306838,1307040,22063,N,N,N,N,65095,14401,9858,5941,2921,10238,10185,11551,1797,716,352,0,729,84027,101011,28890,30509,16279,6544,4887871,3394273,1349621,62780,89230,5925,93147,4887871,211485,127838,26822,4943,51882,4676386,3192169,1298603,20450,64942,1797,6970,91455,3111,88344,2274711,3712212,1763395,1948817
24,Indiana,6691878,3295973,3395905,417774,430155,451395,459222,465439,874246,826473,841750,447600,426678,613699,310870,126577,6691878,5539927,637277,14040,1877,253,84,652,154220,43709,33644,14346,5519,9780,10075,37147,3470,996,1047,452,975,162303,180641,81088,24258,27827,3376,6691878,5703463,739547,48290,193559,11281,191174,6691878,472419,359126,37370,4333,71590,6219459,5266285,628603,10560,152940,3249,15103,142719,3977,138742,2903576,4935180,2392487,2542693
25,Kentucky,4468402,2199021,2269381,273489,279978,285833,288944,300744,579520,553107,575373,304711,295311,435465,217279,78648,4468402,3875023,354761,8470,2926,665,106,110,65300,14340,13302,6224,4806,5148,5819,15661,4943,610,1264,209,2860,51887,108018,55367,13712,14891,2456,4468402,3974518,422416,29444,87095,9563,62137,4468402,161506,85810,15876,14655,45165,4306896,3776055,349542,6878,64830,4003,8661,96927,2713,94214,1995187,3368919,1632285,1736634
26,Louisiana,4659978,2276530,2383448,301857,297439,317930,308126,308893,645255,589714,567313,303589,299252,434897,211869,73844,4659978,2877115,1509407,25657,N,N,N,N,76255,9858,11547,11479,1172,2534,29392,10273,1133,N,N,N,N,65366,105045,38391,20981,17416,6949,4659978,2966465,1565302,58123,101220,6181,75404,4659978,239954,92142,14472,10555,122785,4420024,2720774,1499008,22714,74845,606,10835,91242,2441,88801,2076136,3459079,1655923,1803156
27,Tennessee,6770010,3302191,3467819,404439,413172,434765,439465,437346,914783,846438,883961,445131,445713,658560,332775,113462,6770010,5235588,1137801,19136,5325,176,663,92,119046,26391,21534,11865,5158,9488,14882,29728,5494,1178,1657,1193,1466,101153,151792,64359,28229,27614,3996,6770010,5373382,1217973,55944,155876,12962,115232,6770010,372901,217875,37537,11614,105875,6397109,4984848,1123551,15812,118553,4189,15771,134385,3499,130886,2992412,5075166,2427806,2647360
28,Vermont,626299,308118,318181,28810,32019,33938,42229,43479,75058,70113,80695,47049,49034,75755,34971,13149,626299,589337,7621,1743,N,N,N,N,11859,922,3587,1428,208,1623,427,3664,139,N,N,N,N,2815,12785,2781,4639,2824,261,626299,600494,12187,7315,15706,806,3240,626299,12450,3467,2231,786,5966,613849,579944,7206,1701,11841,139,1143,11875,245,11630,337133,500274,244517,255757
29,Washington,7535591,3766859,3768732,458194,466487,468155,452515,475177,1153369,1006328,930921,488025,472433,710781,325150,128056,7535591,5633263,291808,97329,3544,1844,782,2214,661781,128356,150344,100877,38846,66990,84125,92243,53924,7135,12067,15187,19535,344853,452633,81176,88978,142017,8886,7535591,6041370,422547,226088,857031,95373,398348,7535591,970353,767821,38591,9015,154926,6565238,5111274,281902,81400,655415,52145,14078,369024,8582,360442,3148084,5355539,2655643,2699896
30,Michigan,9995915,4926816,5069099,569183,587011,619055,660528,690292,1291353,1165562,1290759,700756,700963,1009186,506974,204293,9995915,7825285,1376751,53012,1306,26133,581,304,325828,117983,60872,26962,13900,27174,21132,57805,3907,822,1143,795,1147,118467,292665,107343,67048,54569,9727,9995915,8092824,1519646,146197,393744,11157,145988,9995915,517381,374225,47412,12648,83096,9478534,7476047,1363183,46417,324358,3290,14443,250796,7156,243640,4614552,7542878,3667806,3875072

# Finding the datatypes in a dataframe

In [43]:
df.dtypes

Geographic Area Name                                                                                                                                                object
Estimate!!SEX AND AGE!!Total population                                                                                                                             int64
Estimate!!SEX AND AGE!!Total population!!Male                                                                                                                       int64
Estimate!!SEX AND AGE!!Total population!!Female                                                                                                                     int64
Estimate!!SEX AND AGE!!Total population!!Under 5 years                                                                                                              int64
Estimate!!SEX AND AGE!!Total population!!5 to 9 years                                                                                                               int64
Estimate!!SEX AND AGE!!Total population!!10 to 14 years                                                                                                             int64
Estimate!!SEX AND AGE!!Total population!!15 to 19 years                                                                                                             int64
Estimate!!SEX AND AGE!!Total population!!20 to 24 years                                                                                                             int64
Estimate!!SEX AND AGE!!Total population!!25 to 34 years                                                                                                             int64
Estimate!!SEX AND AGE!!Total population!!35 to 44 years                                                                                                             int64
Estimate!!SEX AND AGE!!Total population!!45 to 54 years                                                                                                             int64
Estimate!!SEX AND AGE!!Total population!!55 to 59 years                                                                                                             int64
Estimate!!SEX AND AGE!!Total population!!60 to 64 years                                                                                                             int64
Estimate!!SEX AND AGE!!Total population!!65 to 74 years                                                                                                             int64
Estimate!!SEX AND AGE!!Total population!!75 to 84 years                                                                                                             int64
Estimate!!SEX AND AGE!!Total population!!85 years and over                                                                                                          int64
Estimate!!RACE!!Total population                                                                                                                                    int64
Estimate!!RACE!!Total population!!One race!!White                                                                                                                   int64
Estimate!!RACE!!Total population!!One race!!Black or African American                                                                                               int64
Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native                                                                                       int64
Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping                                                             object
Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping                                                             object
Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping                                                               object
Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping                                                                object
Estimate!!RACE!!Total population!!One race!!Asian                                                                                                                   int64
Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian                                                                                                     object
Estimate!!RACE!!Total population!!One race!!Asian!!Chinese                                                                                                          object
Estimate!!RACE!!Total population!!One race!!Asian!!Filipino                                                                                                         object
Estimate!!RACE!!Total population!!One race!!Asian!!Japanese                                                                                                         object
Estimate!!RACE!!Total population!!One race!!Asian!!Korean                                                                                                           object
Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese                                                                                                       object
Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian                                                                                                      object
Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander                                                                              int64
Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian                                                             object
Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro                                                       object
Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan                                                                      object
Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander                                                      object
Estimate!!RACE!!Total population!!One race!!Some other race                                                                                                         int64
Estimate!!RACE!!Total population!!Two or more races                                                                                                                 int64
Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American                                                                            int64
Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native                                                                    int64
Estimate!!RACE!!Total population!!Two or more races!!White and Asian                                                                                                int64
Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native                                                int64
Estimate!!Race alone or in combination with one or more other races!!Total population                                                                               int64
Estimate!!Race alone or in combination with one or more other races!!Total population!!White                                                                        int64
Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American                                                    int64
Estimate!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native                                            int64
Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian                                                                        int64
Estimate!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander                                   int64
Estimate!!Race alone or in combination with one or more other races!!Total population!!Some other race                                                              int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population                                                                                                             int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)                                                                           int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican                                                                  int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican                                                             int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban                                                                    int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino                                                 int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino                                                                                     int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone                                                                        int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone                                                    int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone                                            int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone                                                                        int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone                                   int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone                                                              int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races                                                                  int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race                             int64
Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races    int64
Estimate!!Total housing units                                                                                                                                       int64
Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population                                                                                           int64
Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male                                                                                     int64
Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female                                                                                   int64
dtype: object

# EDA

# To check whether there is a null value in a dataframe

In [44]:
df.isnull().values.any()

False

# Instead of NA values, we could see there is a value N

Replacing the N values as 0

In [45]:
df1 = df.replace(to_replace = 'N', value = 0)

First N value found in state West Virginia, so instead of taking whole dataframe, checking for the state West Virginia whether the N value has replaced with value 0

In [48]:
df2 = pd.DataFrame(columns=df.columns)

cond = df1['Geographic Area Name'] == 'West Virginia'
rows = df1.loc[cond, :]
df2 = df2.append(rows, ignore_index=True)

In [49]:
df2.head(5)

,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Under 5 years,Estimate!!SEX AND AGE!!Total population!!5 to 9 years,Estimate!!SEX AND AGE!!Total population!!10 to 14 years,Estimate!!SEX AND AGE!!Total population!!15 to 19 years,Estimate!!SEX AND AGE!!Total population!!20 to 24 years,Estimate!!SEX AND AGE!!Total population!!25 to 34 years,Estimate!!SEX AND AGE!!Total population!!35 to 44 years,Estimate!!SEX AND AGE!!Total population!!45 to 54 years,Estimate!!SEX AND AGE!!Total population!!55 to 59 years,Estimate!!SEX AND AGE!!Total population!!60 to 64 years,Estimate!!SEX AND AGE!!Total population!!65 to 74 years,Estimate!!SEX AND AGE!!Total population!!75 to 84 years,Estimate!!SEX AND AGE!!Total population!!85 years and over,Estimate!!RACE!!Total population,Estimate!!RACE!!Total population!!One race!!White,Estimate!!RACE!!Total population!!One race!!Black or African American,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping,Estimate!!RACE!!Total population!!One race!!Asian,Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian,Estimate!!RACE!!Total population!!One race!!Asian!!Chinese,Estimate!!RACE!!Total population!!One race!!Asian!!Filipino,Estimate!!RACE!!Total population!!One race!!Asian!!Japanese,Estimate!!RACE!!Total population!!One race!!Asian!!Korean,Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese,Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Some other race,Estimate!!RACE!!Total population!!Two or more races,Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American,Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native,Estimate!!RACE!!Total population!!Two or more races!!White and Asian,Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population,Estimate!!Race alone or in combination with one or more other races!!Total population!!White,Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Estimate!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian,Estimate!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander,Estimate!!Race alone or in combination with one or more other races!!Total population!!Some other race,Estimate!!HISPANIC OR LATINO AND RACE!!Total population,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race,"Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Estimate!!Total housing units,"Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female"
0,West Virginia,1805832,894657,911175,93922,97203,107390,112776,113760,209002,218803,233109,127449,131202,215290,105707,40219,1805832,1679773,68679,2629,0,0,0,0,13459,2331,3893,1994,686,1396,1137,2022,451,0,0,0,0,6430,34411,19582,5340,4574,200,1805832,1712618,89894,9599,19875,2577,8067,1805832,25569,11319,4112,1351,8787,1780263,1661773,68042,2535,13311,451,2286,31865,335,31530,893742,1431158,701390,729768

In [50]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', -1)

# Replacing the N Values as mean value of the column

In [54]:
Native_Hawaiin = df2[df2["Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian"]!= 'N']["Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian"]

df2["Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian"].replace('N',Native_Hawaiin.mean())


#df3 = df2.replace(to_replace = 'N', value = 0)

0    0
Name: Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian, dtype: int64

In [55]:
df2.head(5)

,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Under 5 years,Estimate!!SEX AND AGE!!Total population!!5 to 9 years,Estimate!!SEX AND AGE!!Total population!!10 to 14 years,Estimate!!SEX AND AGE!!Total population!!15 to 19 years,Estimate!!SEX AND AGE!!Total population!!20 to 24 years,Estimate!!SEX AND AGE!!Total population!!25 to 34 years,Estimate!!SEX AND AGE!!Total population!!35 to 44 years,Estimate!!SEX AND AGE!!Total population!!45 to 54 years,Estimate!!SEX AND AGE!!Total population!!55 to 59 years,Estimate!!SEX AND AGE!!Total population!!60 to 64 years,Estimate!!SEX AND AGE!!Total population!!65 to 74 years,Estimate!!SEX AND AGE!!Total population!!75 to 84 years,Estimate!!SEX AND AGE!!Total population!!85 years and over,Estimate!!RACE!!Total population,Estimate!!RACE!!Total population!!One race!!White,Estimate!!RACE!!Total population!!One race!!Black or African American,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping,Estimate!!RACE!!Total population!!One race!!Asian,Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian,Estimate!!RACE!!Total population!!One race!!Asian!!Chinese,Estimate!!RACE!!Total population!!One race!!Asian!!Filipino,Estimate!!RACE!!Total population!!One race!!Asian!!Japanese,Estimate!!RACE!!Total population!!One race!!Asian!!Korean,Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese,Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan,Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Estimate!!RACE!!Total population!!One race!!Some other race,Estimate!!RACE!!Total population!!Two or more races,Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American,Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native,Estimate!!RACE!!Total population!!Two or more races!!White and Asian,Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population,Estimate!!Race alone or in combination with one or more other races!!Total population!!White,Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Estimate!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native,Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian,Estimate!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander,Estimate!!Race alone or in combination with one or more other races!!Total population!!Some other race,Estimate!!HISPANIC OR LATINO AND RACE!!Total population,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race,"Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Estimate!!Total housing units,"Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female"
0,West Virginia,1805832,894657,911175,93922,97203,107390,112776,113760,209002,218803,233109,127449,131202,215290,105707,40219,1805832,1679773,68679,2629,0,0,0,0,13459,2331,3893,1994,686,1396,1137,2022,451,0,0,0,0,6430,34411,19582,5340,4574,200,1805832,1712618,89894,9599,19875,2577,8067,1805832,25569,11319,4112,1351,8787,1780263,1661773,68042,2535,13311,451,2286,31865,335,31530,893742,1431158,701390,729768