In [38]:
import pandas as pd
import numpy as np
from functools import reduce

In [39]:
Tab1 = pd.read_excel('Residence_all_tables.xlsx', 'Table 1 Personal Health Care')
Tab2 = pd.read_excel('Residence_all_tables.xlsx', 'Table 2 Hospital')
Tab3 = pd.read_excel('Residence_all_tables.xlsx', 'Table 3 Physician and Clinics')
Tab4 = pd.read_excel('Residence_all_tables.xlsx', 'Table 4 Other Professionals')
Tab6 = pd.read_excel('Residence_all_tables.xlsx', 'Table 6 Home Health')
Tab8 = pd.read_excel('Residence_all_tables.xlsx', 'Table 8 Drugs and Non-durables')
Tab9 = pd.read_excel('Residence_all_tables.xlsx', 'Table 9 Durables')
Tab10 = pd.read_excel('Residence_all_tables.xlsx', 'Table 10 Other Health')

In [40]:
Tab1

,Table 1: Total All Payers State Estimates by State of Residence (1991 - 2014) - Personal Health Care (Millions of Dollars),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Region/state of residence,1991.0,1992.0,1993.0,1994.0,1995.0,1996.0,1997.0,1998.0,1999.0,...,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,Average\nAnnual %\nGrowth\n(1991-2014)
1,United States,675896.0,731455.0,778684.0,820172.0,869578.0,917540.0,969531.0,1026103.0,1086280.0,...,1804672.0,1918820.0,2010690.0,2114221.0,2194625.0,2272582.0,2365948.0,2435624.0,2562824.0,0.06
2,New England,41141.0,43852.0,46559.0,48652.0,52174.0,54893.0,58206.0,62436.0,65393.0,...,108337.0,115472.0,121374.0,128237.0,131705.0,135127.0,139653.0,143519.0,148571.0,0.057
3,Connecticut,10950.0,11635.0,12081.0,12772.0,13649.0,14139.0,14948.0,15944.0,16785.0,...,25997.0,27488.0,29141.0,31132.0,31727.0,32129.0,33421.0,34223.0,35413.0,0.052
4,Maine,3152.0,3326.0,3567.0,3719.0,4052.0,4395.0,4752.0,5151.0,5604.0,...,9760.0,10243.0,10725.0,11114.0,11338.0,11720.0,11961.0,12139.0,12684.0,0.062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Nevada,3086.0,3464.0,3696.0,4102.0,4404.0,4769.0,5211.0,5694.0,6249.0,...,12991.0,14123.0,14907.0,15302.0,15652.0,16198.0,16588.0,17485.0,19020.0,0.082
59,Oregon,6760.0,7458.0,7960.0,8381.0,9022.0,9530.0,10217.0,11369.0,12100.0,...,21077.0,22264.0,23390.0,24697.0,25824.0,26964.0,27757.0,29314.0,31920.0,0.07
60,Washington,12674.0,13859.0,14523.0,15303.0,16515.0,17158.0,17978.0,19746.0,21504.0,...,36500.0,39595.0,42569.0,45589.0,47077.0,48567.0,51443.0,53022.0,55819.0,0.067
61,NOTE: Numbers may not add to totals shown beca...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,SOURCE: Centers for Medicare and Medicaid Serv...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
Tab1 = Tab1.rename(columns = {'Table 1: Total All Payers State Estimates by State of Residence (1991 - 2014) - Personal Health Care (Millions of Dollars)':'State',
                             'Unnamed: 24':'Personal Health Care Expenses Per State (2014)'})
Tab1 = Tab1[['State', 'Personal Health Care Expenses Per State (2014)']]
Tab1

,State,Personal Health Care Expenses Per State (2014)
0,Region/state of residence,2014.0
1,United States,2562824.0
2,New England,148571.0
3,Connecticut,35413.0
4,Maine,12684.0
...,...,...
58,Nevada,19020.0
59,Oregon,31920.0
60,Washington,55819.0
61,NOTE: Numbers may not add to totals shown beca...,NaN
62,SOURCE: Centers for Medicare and Medicaid Serv...,NaN

In [42]:
Tab2 = Tab2.rename(columns = {'Table 2: Total All Payers State Estimates by State of Residence (1991 - 2014) - Hospital Services (Millions of Dollars)':'State',
                             'Unnamed: 24':'Hospital Services Expenses Per State (2014)'})
Tab2 = Tab2[['State', 'Hospital Services Expenses Per State (2014)']]

In [43]:
Tab2.head()

                       State  Hospital Services Expenses Per State (2014)
0  Region/state of residence                                       2014.0
1              United States                                     980966.0
2                New England                                      55504.0
3                Connecticut                                      11947.0
4                      Maine                                       5261.0

In [44]:
Tab3 = Tab3.rename(columns = {'Table 3: Total All Payers State Estimates by State of Residence (1991 - 2014) - Physician and Clinical Services (Millions of Dollars)':'State',
                             'Unnamed: 24':'Pysician and Clincial Services Expenses Per State (2014)'})
Tab3 = Tab3[['State','Pysician and Clincial Services Expenses Per State (2014)']]
Tab3.head()

,State,Pysician and Clincial Services Expenses Per State (2014)
0,Region/state of residence,2014.0
1,United States,597137.0
2,New England,31385.0
3,Connecticut,7852.0
4,Maine,2240.0

In [45]:
Tab4 = Tab4.rename(columns = {'Table 4: Total All Payers State Estimates by State of Residence (1991 - 2014) - Other Professional Services (Millions of Dollars)':'State',
                             'Unnamed: 24':'Other Professional Services Expenses Per State (2014)'})
Tab4 = Tab4[['State', 'Other Professional Services Expenses Per State (2014)']]
Tab4.head()

,State,Other Professional Services Expenses Per State (2014)
0,Region/state of residence,2014.0
1,United States,82826.0
2,New England,4506.0
3,Connecticut,1156.0
4,Maine,438.0

In [46]:
Tab6 = Tab6.rename(columns = {'Table 6: Total All Payers State Estimates by State of Residence (1991 - 2014) - Home Health Care (Millions of Dollars)':'State',
                             'Unnamed: 24':'Home Health Care Expenses Per State (2014)'})
Tab6 = Tab6[['State','Home Health Care Expenses Per State (2014)']]
Tab6.head()

                       State  Home Health Care Expenses Per State (2014)
0  Region/state of residence                                      2014.0
1              United States                                     83566.0
2                New England                                      6592.0
3                Connecticut                                      1062.0
4                      Maine                                       270.0

In [47]:
Tab8 = Tab8.rename(columns = {'Table 8: Total All Payers State Estimates by State of Residence (1991 - 2014) - Drugs and Other Non-durable Products  (Millions of Dollars)':'State',
                             'Unnamed: 24':'Drugs and Non-Durables Expenses Per State (2014)'})
Tab8 = Tab8[['State','Drugs and Non-Durables Expenses Per State (2014)']]
Tab8.head()

                       State  Drugs and Non-Durables Expenses Per State (2014)
0  Region/state of residence                                            2014.0
1              United States                                          354784.0
2                New England                                           19116.0
3                Connecticut                                            5300.0
4                      Maine                                            1542.0

In [48]:
Tab9 = Tab9.rename(columns = {'Table 9: Total All Payers State Estimates by State of Residence (1991 - 2014) - Durable Medical Equipment  (Millions of Dollars)':'State',
                             'Unnamed: 24':'Durables Expenses Per State (2014)'})
Tab9 = Tab9[['State','Durables Expenses Per State (2014)']]
Tab9.head()

                       State  Durables Expenses Per State (2014)
0  Region/state of residence                              2014.0
1              United States                             46622.0
2                New England                              2319.0
3                Connecticut                               506.0
4                      Maine                               183.0

In [49]:
Tab10 = Tab10.rename(columns = {'Table 10: Total All Payers State Estimates by State of Residence (1991 - 2014) - Other Health Residential and Personal Care (Millions of Dollars)':'State',
                             'Unnamed: 24':'Other Health Care Expenses Per State (2014)'})
Tab10 = Tab10[['State','Other Health Care Expenses Per State (2014)']]
Tab10.head()

                       State  Other Health Care Expenses Per State (2014)
0  Region/state of residence                                       2014.0
1              United States                                     151456.0
2                New England                                      11747.0
3                Connecticut                                       2839.0
4                      Maine                                       1463.0

In [50]:
PerStateDF = [Tab1, Tab2, Tab3, Tab4, Tab6, Tab8, Tab9, Tab10]
PerStateFinal = reduce(lambda left, right: pd.merge(left, right, on = 'State', how = 'outer'), PerStateDF)
PerStateFinal.head()

,State,Personal Health Care Expenses Per State (2014),Hospital Services Expenses Per State (2014),Pysician and Clincial Services Expenses Per State (2014),Other Professional Services Expenses Per State (2014),Home Health Care Expenses Per State (2014),Drugs and Non-Durables Expenses Per State (2014),Durables Expenses Per State (2014),Other Health Care Expenses Per State (2014)
0,Region/state of residence,2014.0,2014.0,2014.0,2014.0,2014.0,2014.0,2014.0,2014.0
1,United States,2562824.0,980966.0,597137.0,82826.0,83566.0,354784.0,46622.0,151456.0
2,New England,148571.0,55504.0,31385.0,4506.0,6592.0,19116.0,2319.0,11747.0
3,Connecticut,35413.0,11947.0,7852.0,1156.0,1062.0,5300.0,506.0,2839.0
4,Maine,12684.0,5261.0,2240.0,438.0,270.0,1542.0,183.0,1463.0

In [51]:
COVIDCases = pd.read_csv('us-states.csv')
COVIDCases = COVIDCases.groupby(['state']).sum()
COVIDCases = COVIDCases.reset_index()
COVIDCases.drop([11, 36, 41, 49], inplace = True)
COVIDCases = COVIDCases.reset_index(drop = True)
COVIDCases.state

0                  Alabama
1                   Alaska
2                  Arizona
3                 Arkansas
4               California
5                 Colorado
6              Connecticut
7                 Delaware
8     District of Columbia
9                  Florida
10                 Georgia
11                  Hawaii
12                   Idaho
13                Illinois
14                 Indiana
15                    Iowa
16                  Kansas
17                Kentucky
18               Louisiana
19                   Maine
20                Maryland
21           Massachusetts
22                Michigan
23               Minnesota
24             Mississippi
25                Missouri
26                 Montana
27                Nebraska
28                  Nevada
29           New Hampshire
30              New Jersey
31              New Mexico
32                New York
33          North Carolina
34            North Dakota
35                    Ohio
36                Oklahoma
37                  Oregon
38            Pennsylvania
39            Rhode Island
40          South Carolina
41            South Dakota
42               Tennessee
43                   Texas
44                    Utah
45                 Vermont
46                Virginia
47              Washington
48           West Virginia
49               Wisconsin
50                 Wyoming
Name: state, dtype: object

In [52]:
COVIDCases = COVIDCases.rename(columns = {'state':'State'})
COVIDCases.head()

        State  fips    cases  deaths
0     Alabama    73   387786   14345
1      Alaska   148    18316     367
2     Arizona   480   426614   18857
3    Arkansas   375   161569    3301
4  California   726  2664110  102387

In [53]:
COVIDHealthPerState = pd.merge(COVIDCases, PerStateFinal, how = 'left', on = 'State')
COVIDHealthPerState

,State,fips,cases,deaths,Personal Health Care Expenses Per State (2014),Hospital Services Expenses Per State (2014),Pysician and Clincial Services Expenses Per State (2014),Other Professional Services Expenses Per State (2014),Home Health Care Expenses Per State (2014),Drugs and Non-Durables Expenses Per State (2014),Durables Expenses Per State (2014),Other Health Care Expenses Per State (2014)
0,Alabama,73,387786,14345,35263.0,12715.0,8423.0,826.0,980.0,6816.0,686.0,1569.0
1,Alaska,148,18316,367,8151.0,3473.0,2481.0,342.0,144.0,471.0,102.0,587.0
2,Arizona,480,426614,18857,43356.0,15707.0,11922.0,1666.0,913.0,5467.0,1173.0,2332.0
3,Arkansas,375,161569,3301,21980.0,7930.0,4851.0,776.0,538.0,3470.0,308.0,1885.0
4,California,726,2664110,102387,291989.0,106487.0,76688.0,8376.0,11253.0,36924.0,3740.0,19164.0
5,Colorado,648,766512,37828,36398.0,14650.0,8572.0,1739.0,1026.0,3642.0,919.0,1552.0
6,Connecticut,702,1314995,104185,35413.0,11947.0,7852.0,1156.0,1062.0,5300.0,506.0,2839.0
7,Delaware,750,234327,7813,9587.0,3812.0,2112.0,326.0,224.0,1425.0,184.0,553.0
8,District of Columbia,869,229466,10822,7871.0,3449.0,1619.0,147.0,430.0,771.0,76.0,724.0
9,Florida,1020,1726811,63147,160624.0,54339.0,43592.0,5983.0,5846.0,24504.0,5025.0,5052.0
10,Georgia,1092,1282091,54209,66447.0,24676.0,18325.0,2130.0,1644.0,9467.0,1410.0,2615.0
11,Hawaii,1200,31433,681,10338.0,3914.0,2722.0,330.0,230.0,1673.0,240.0,246.0
12,Idaho,1168,103987,2828,11315.0,4963.0,2165.0,493.0,292.0,1301.0,244.0,625.0
13,Illinois,2074,2843621,122000,106306.0,43497.0,24139.0,4365.0,2805.0,12949.0,1652.0,5652.0
14,Indiana,1440,920434,53042,54741.0,23027.0,12144.0,1593.0,1069.0,7383.0,1082.0,2450.0
15,Iowa,1482,396980,9203,25487.0,10231.0,4826.0,814.0,548.0,3568.0,433.0,1914.0
16,Kansas,1580,231885,6527,22183.0,8593.0,4935.0,773.0,400.0,3243.0,363.0,1209.0
17,Kentucky,1680,246480,11851,35323.0,14198.0,8077.0,1008.0,705.0,5289.0,657.0,2106.0
18,Louisiana,1694,1443404,90609,36324.0,14174.0,7988.0,1104.0,1316.0,5841.0,471.0,2226.0
19,Maine,1702,61284,2451,12684.0,5261.0,2240.0,438.0,270.0,1542.0,183.0,1463.0
20,Maryland,1944,1173802,56126,51330.0,19589.0,12611.0,1644.0,1055.0,6847.0,751.0,2877.0
21,Massachusetts,2850,2929874,167711,71274.0,26544.0,15280.0,2034.0,4503.0,8437.0,1150.0,5225.0
22,Michigan,1976,2023047,171867,79874.0,32287.0,17232.0,2626.0,2861.0,10964.0,2708.0,2706.0
23,Minnesota,2160,377850,18934,48377.0,18396.0,9589.0,1470.0,2860.0,5206.0,735.0,4730.0
24,Mississippi,2100,358459,15047,22879.0,9658.0,4682.0,568.0,635.0,3386.0,493.0,1353.0
25,Missouri,2291,395952,17924,49137.0,21164.0,9346.0,1380.0,1374.0,7717.0,646.0,2505.0
26,Montana,2190,23875,676,8409.0,3807.0,1696.0,310.0,155.0,885.0,169.0,559.0
27,Nebraska,3038,259429,3535,15823.0,6568.0,3306.0,557.0,182.0,2336.0,348.0,775.0
28,Nevada,2592,259808,11975,19020.0,6730.0,5304.0,773.0,661.0,2736.0,426.0,691.0
29,New Hampshire,2772,117245,4507,12742.0,5010.0,2960.0,349.0,303.0,1623.0,254.0,759.0
30,New Jersey,2788,5645458,332869,79066.0,26014.0,21148.0,3222.0,2178.0,12089.0,1418.0,4269.0
31,New Mexico,2625,177827,6867,15027.0,6595.0,3314.0,558.0,522.0,1558.0,430.0,737.0
32,New York,3060,15041806,1081194,192809.0,71630.0,36941.0,5891.0,9426.0,28294.0,2834.0,18459.0
33,North Carolina,3071,568719,19258,72160.0,27606.0,16014.0,2196.0,1941.0,12295.0,1411.0,2648.0
34,North Dakota,2850,55932,1219,7289.0,3314.0,1268.0,193.0,54.0,869.0,122.0,600.0
35,Ohio,3003,908834,47879,101013.0,44167.0,20626.0,2699.0,3007.0,11866.0,1668.0,6287.0
36,Oklahoma,3200,187462,10394,29575.0,12089.0,6404.0,1007.0,755.0,4576.0,448.0,1392.0
37,Oregon,3567,134979,5067,31920.0,11666.0,7455.0,1311.0,661.0,3501.0,513.0,3146.0
38,Pennsylvania,3360,2320771,127278,118419.0,43693.0,25156.0,3940.0,3122.0,17208.0,1807.0,9550.0
39,Rhode Island,3740,401931,14251,10071.0,3814.0,1956.0,328.0,266.0,1488.0,145.0,936.0
40,South Carolina,3600,313173,11859,35299.0,14161.0,7810.0,987.0,1056.0,5758.0,745.0,1393.0
41,South Dakota,3496,122292,1121,7616.0,3764.0,1394.0,218.0,79.0,809.0,108.0,399.0
42,Tennessee,3807,583792,10198,48249.0,17124.0,12303.0,1433.0,1402.0,7960.0,888.0,2557.0
43,Texas,4944,1553075,41267,188559.0,72704.0,45665.0,5591.0,7604.0,28916.0,3107.0,8970.0
44,Utah,4410,245859,2472,17597.0,6915.0,3881.0,624.0,553.0,2305.0,473.0,1062.0
45,Vermont,3950,45230,2320,6389.0,2928.0,1097.0,201.0,189.0,726.0,81.0,525.0
46,Virginia,4029,866807,28754,62847.0,24222.0,15610.0,1868.0,1268.0,8439.0,1123.0,3493.0
47,Washington,6625,807848,42371,55819.0,21797.0,14562.0,2282.0,1326.0,5610.0,1030.0,2444.0
48,West Virginia,3726,56158,1950,17491.0,7463.0,3340.0,439.0,503.0,2545.0,343.0,1313.0
49,Wisconsin,6050,393823,15587,50109.0,20165.0,12482.0,1518.0,1325.0,6349.0,719.0,2088.0
50,Wyoming,4200,28407,281,4856.0,2335.0,1034.0,220.0,45.0,438.0,75.0,243.0

In [54]:
COVIDHealthPerState = COVIDHealthPerState.drop(['fips'], axis = 1)
COVIDHealthPerState

,State,cases,deaths,Personal Health Care Expenses Per State (2014),Hospital Services Expenses Per State (2014),Pysician and Clincial Services Expenses Per State (2014),Other Professional Services Expenses Per State (2014),Home Health Care Expenses Per State (2014),Drugs and Non-Durables Expenses Per State (2014),Durables Expenses Per State (2014),Other Health Care Expenses Per State (2014)
0,Alabama,387786,14345,35263.0,12715.0,8423.0,826.0,980.0,6816.0,686.0,1569.0
1,Alaska,18316,367,8151.0,3473.0,2481.0,342.0,144.0,471.0,102.0,587.0
2,Arizona,426614,18857,43356.0,15707.0,11922.0,1666.0,913.0,5467.0,1173.0,2332.0
3,Arkansas,161569,3301,21980.0,7930.0,4851.0,776.0,538.0,3470.0,308.0,1885.0
4,California,2664110,102387,291989.0,106487.0,76688.0,8376.0,11253.0,36924.0,3740.0,19164.0
5,Colorado,766512,37828,36398.0,14650.0,8572.0,1739.0,1026.0,3642.0,919.0,1552.0
6,Connecticut,1314995,104185,35413.0,11947.0,7852.0,1156.0,1062.0,5300.0,506.0,2839.0
7,Delaware,234327,7813,9587.0,3812.0,2112.0,326.0,224.0,1425.0,184.0,553.0
8,District of Columbia,229466,10822,7871.0,3449.0,1619.0,147.0,430.0,771.0,76.0,724.0
9,Florida,1726811,63147,160624.0,54339.0,43592.0,5983.0,5846.0,24504.0,5025.0,5052.0
10,Georgia,1282091,54209,66447.0,24676.0,18325.0,2130.0,1644.0,9467.0,1410.0,2615.0
11,Hawaii,31433,681,10338.0,3914.0,2722.0,330.0,230.0,1673.0,240.0,246.0
12,Idaho,103987,2828,11315.0,4963.0,2165.0,493.0,292.0,1301.0,244.0,625.0
13,Illinois,2843621,122000,106306.0,43497.0,24139.0,4365.0,2805.0,12949.0,1652.0,5652.0
14,Indiana,920434,53042,54741.0,23027.0,12144.0,1593.0,1069.0,7383.0,1082.0,2450.0
15,Iowa,396980,9203,25487.0,10231.0,4826.0,814.0,548.0,3568.0,433.0,1914.0
16,Kansas,231885,6527,22183.0,8593.0,4935.0,773.0,400.0,3243.0,363.0,1209.0
17,Kentucky,246480,11851,35323.0,14198.0,8077.0,1008.0,705.0,5289.0,657.0,2106.0
18,Louisiana,1443404,90609,36324.0,14174.0,7988.0,1104.0,1316.0,5841.0,471.0,2226.0
19,Maine,61284,2451,12684.0,5261.0,2240.0,438.0,270.0,1542.0,183.0,1463.0
20,Maryland,1173802,56126,51330.0,19589.0,12611.0,1644.0,1055.0,6847.0,751.0,2877.0
21,Massachusetts,2929874,167711,71274.0,26544.0,15280.0,2034.0,4503.0,8437.0,1150.0,5225.0
22,Michigan,2023047,171867,79874.0,32287.0,17232.0,2626.0,2861.0,10964.0,2708.0,2706.0
23,Minnesota,377850,18934,48377.0,18396.0,9589.0,1470.0,2860.0,5206.0,735.0,4730.0
24,Mississippi,358459,15047,22879.0,9658.0,4682.0,568.0,635.0,3386.0,493.0,1353.0
25,Missouri,395952,17924,49137.0,21164.0,9346.0,1380.0,1374.0,7717.0,646.0,2505.0
26,Montana,23875,676,8409.0,3807.0,1696.0,310.0,155.0,885.0,169.0,559.0
27,Nebraska,259429,3535,15823.0,6568.0,3306.0,557.0,182.0,2336.0,348.0,775.0
28,Nevada,259808,11975,19020.0,6730.0,5304.0,773.0,661.0,2736.0,426.0,691.0
29,New Hampshire,117245,4507,12742.0,5010.0,2960.0,349.0,303.0,1623.0,254.0,759.0
30,New Jersey,5645458,332869,79066.0,26014.0,21148.0,3222.0,2178.0,12089.0,1418.0,4269.0
31,New Mexico,177827,6867,15027.0,6595.0,3314.0,558.0,522.0,1558.0,430.0,737.0
32,New York,15041806,1081194,192809.0,71630.0,36941.0,5891.0,9426.0,28294.0,2834.0,18459.0
33,North Carolina,568719,19258,72160.0,27606.0,16014.0,2196.0,1941.0,12295.0,1411.0,2648.0
34,North Dakota,55932,1219,7289.0,3314.0,1268.0,193.0,54.0,869.0,122.0,600.0
35,Ohio,908834,47879,101013.0,44167.0,20626.0,2699.0,3007.0,11866.0,1668.0,6287.0
36,Oklahoma,187462,10394,29575.0,12089.0,6404.0,1007.0,755.0,4576.0,448.0,1392.0
37,Oregon,134979,5067,31920.0,11666.0,7455.0,1311.0,661.0,3501.0,513.0,3146.0
38,Pennsylvania,2320771,127278,118419.0,43693.0,25156.0,3940.0,3122.0,17208.0,1807.0,9550.0
39,Rhode Island,401931,14251,10071.0,3814.0,1956.0,328.0,266.0,1488.0,145.0,936.0
40,South Carolina,313173,11859,35299.0,14161.0,7810.0,987.0,1056.0,5758.0,745.0,1393.0
41,South Dakota,122292,1121,7616.0,3764.0,1394.0,218.0,79.0,809.0,108.0,399.0
42,Tennessee,583792,10198,48249.0,17124.0,12303.0,1433.0,1402.0,7960.0,888.0,2557.0
43,Texas,1553075,41267,188559.0,72704.0,45665.0,5591.0,7604.0,28916.0,3107.0,8970.0
44,Utah,245859,2472,17597.0,6915.0,3881.0,624.0,553.0,2305.0,473.0,1062.0
45,Vermont,45230,2320,6389.0,2928.0,1097.0,201.0,189.0,726.0,81.0,525.0
46,Virginia,866807,28754,62847.0,24222.0,15610.0,1868.0,1268.0,8439.0,1123.0,3493.0
47,Washington,807848,42371,55819.0,21797.0,14562.0,2282.0,1326.0,5610.0,1030.0,2444.0
48,West Virginia,56158,1950,17491.0,7463.0,3340.0,439.0,503.0,2545.0,343.0,1313.0
49,Wisconsin,393823,15587,50109.0,20165.0,12482.0,1518.0,1325.0,6349.0,719.0,2088.0
50,Wyoming,28407,281,4856.0,2335.0,1034.0,220.0,45.0,438.0,75.0,243.0