In [1]:
import pandas as pd
import numpy as np
from functools import reduce

In [3]:
Tab11 = pd.read_excel('Residence_all_tables.xlsx', 'Table 11 Personal Health Care')
Tab12 = pd.read_excel('Residence_all_tables.xlsx', ' Table 12 Hospital')
Tab13 = pd.read_excel('Residence_all_tables.xlsx', 'Table 13 Physician and Clinics')
Tab14 = pd.read_excel('Residence_all_tables.xlsx', 'Table 14 Other Professional')
Tab16 = pd.read_excel('Residence_all_tables.xlsx', 'Table 16 Home Health Care')
Tab18 = pd.read_excel('Residence_all_tables.xlsx', 'Table 18 Drugs and Non-durables')
Tab19 = pd.read_excel('Residence_all_tables.xlsx', 'Table 19 Durables')
Tab20 = pd.read_excel('Residence_all_tables.xlsx', 'Table 20 Other Health')

In [4]:
Tab11 = Tab11.rename(columns = {'Table 11: Total All Payers Per Capita State Estimates by State of Residence (1991 - 2014) - Personal Health Care (Dollars)':'State',
                             'Unnamed: 24':'Personal Health Care Expenses Per State Capita (2014)'})
Tab11 = Tab11[['State', 'Personal Health Care Expenses Per State Capita (2014)']]
Tab11.head()

,State,Personal Health Care Expenses Per State Capita (2014)
0,Region/state of residence,2014.0
1,United States,8045.0
2,New England,10119.0
3,Connecticut,9859.0
4,Maine,9531.0

In [7]:
Tab12 = Tab12.rename(columns = {'Table 12: Total All Payers Per Capita State Estimates by State of Residence (1991 - 2014) - Hospital Services (Dollars)':'State',
                             'Unnamed: 24':'Hospital Services Expenses Per State Capita (2014)'})
Tab12 = Tab12[['State', 'Hospital Services Expenses Per State Capita (2014)']]
Tab12.head()

,State,Hospital Services Expenses Per State Capita (2014)
0,Region/state of residence,2014.0
1,United States,3079.0
2,New England,3780.0
3,Connecticut,3326.0
4,Maine,3953.0

In [8]:
Tab13 = Tab13.rename(columns = {'Table 13: Total All Payers Per Capita State Estimates by State of Residence (1991 - 2014) - Physician and Clinical Services (Dollars)':'State',
                             'Unnamed: 24':'Physician and Clinical Services Expenses Per State Capita (2014)'})
Tab13 = Tab13[['State', 'Physician and Clinical Services Expenses Per State Capita (2014)']]
Tab13.head()

,State,Physician and Clinical Services Expenses Per State Capita (2014)
0,Region/state of residence,2014.0
1,United States,1874.0
2,New England,2138.0
3,Connecticut,2186.0
4,Maine,1684.0

In [9]:
Tab14 = Tab14.rename(columns = {'Table 14: Total All Payers Per Capita State Estimates by State of Residence (1991 - 2014) - Other Professional Services (Dollars)':'State',
                             'Unnamed: 24':'Other Professional Services Expenses Per State Capita (2014)'})
Tab14 = Tab14[['State', 'Other Professional Services Expenses Per State Capita (2014)']]
Tab14.head()

,State,Other Professional Services Expenses Per State Capita (2014)
0,Region/state of residence,2014.0
1,United States,260.0
2,New England,307.0
3,Connecticut,322.0
4,Maine,329.0

In [10]:
Tab16 = Tab16.rename(columns = {'Table 16: Total All Payers Per Capita State Estimates by State of Residence (1991 - 2014) - Home Health Care (Dollars)':'State',
                             'Unnamed: 24':'Home Health Care Expenses Per State Capita (2014)'})
Tab16 = Tab16[['State', 'Home Health Care Expenses Per State Capita (2014)']]
Tab16.head()

,State,Home Health Care Expenses Per State Capita (2014)
0,Region/state of residence,2014.0
1,United States,262.0
2,New England,449.0
3,Connecticut,296.0
4,Maine,203.0

In [11]:
Tab18 = Tab18.rename(columns = {'Table 18: Total All Payers Per Capita State Estimates by State of Residence (1991 - 2014) - Drugs and Other Non-durable Products (Dollars)':'State',
                             'Unnamed: 24':'Drugs and Non-Durables Expenses Per State Capita (2014)'})
Tab18 = Tab18[['State', 'Drugs and Non-Durables Expenses Per State Capita (2014)']]
Tab18.head()

,State,Drugs and Non-Durables Expenses Per State Capita (2014)
0,Region/state of residence,2014.0
1,United States,1114.0
2,New England,1302.0
3,Connecticut,1476.0
4,Maine,1159.0

In [12]:
Tab19 = Tab19.rename(columns = {'Table 19: Total All Payers Per Capita State Estimates by State of Residence (1991 - 2014) - Durable Medical Equipment  (Dollars)':'State',
                             'Unnamed: 24':'Durables Expenses Per State Capita (2014)'})
Tab19 = Tab19[['State', 'Durables Expenses Per State Capita (2014)']]
Tab19.head()

                       State  Durables Expenses Per State Capita (2014)
0  Region/state of residence                                     2014.0
1              United States                                      146.0
2                New England                                      158.0
3                Connecticut                                      141.0
4                      Maine                                      137.0

In [13]:
Tab20 = Tab20.rename(columns = {'Table 20: Total All Payers Per Capita State Estimates by State of Residence (1991 - 2014) - Other Health Residential and Personal Care (Dollars)':'State',
                             'Unnamed: 24':'Other Health Care Expenses Per State Capita (2014)'})
Tab20 = Tab20[['State', 'Other Health Care Expenses Per State Capita (2014)']]
Tab20.head()

,State,Other Health Care Expenses Per State Capita (2014)
0,Region/state of residence,2014.0
1,United States,475.0
2,New England,800.0
3,Connecticut,790.0
4,Maine,1100.0

In [14]:
PerStateCapitaDF = [Tab11, Tab12, Tab13, Tab14, Tab16, Tab18, Tab19, Tab20]
PerStateCapitaFinal = reduce(lambda left, right: pd.merge(left, right, on = 'State', how = 'outer'), PerStateCapitaDF)
PerStateCapitaFinal.head()

,State,Personal Health Care Expenses Per State Capita (2014),Hospital Services Expenses Per State Capita (2014),Physician and Clinical Services Expenses Per State Capita (2014),Other Professional Services Expenses Per State Capita (2014),Home Health Care Expenses Per State Capita (2014),Drugs and Non-Durables Expenses Per State Capita (2014),Durables Expenses Per State Capita (2014),Other Health Care Expenses Per State Capita (2014)
0,Region/state of residence,2014.0,2014.0,2014.0,2014.0,2014.0,2014.0,2014.0,2014.0
1,United States,8045.0,3079.0,1874.0,260.0,262.0,1114.0,146.0,475.0
2,New England,10119.0,3780.0,2138.0,307.0,449.0,1302.0,158.0,800.0
3,Connecticut,9859.0,3326.0,2186.0,322.0,296.0,1476.0,141.0,790.0
4,Maine,9531.0,3953.0,1684.0,329.0,203.0,1159.0,137.0,1100.0

In [15]:
COVIDCases = pd.read_csv('us-states.csv')
COVIDCases = COVIDCases.groupby(['state']).sum()
COVIDCases = COVIDCases.reset_index()
COVIDCases.drop([11, 36, 41, 49], inplace = True)
COVIDCases = COVIDCases.reset_index(drop = True)
COVIDCases.state

0                  Alabama
1                   Alaska
2                  Arizona
3                 Arkansas
4               California
5                 Colorado
6              Connecticut
7                 Delaware
8     District of Columbia
9                  Florida
10                 Georgia
11                  Hawaii
12                   Idaho
13                Illinois
14                 Indiana
15                    Iowa
16                  Kansas
17                Kentucky
18               Louisiana
19                   Maine
20                Maryland
21           Massachusetts
22                Michigan
23               Minnesota
24             Mississippi
25                Missouri
26                 Montana
27                Nebraska
28                  Nevada
29           New Hampshire
30              New Jersey
31              New Mexico
32                New York
33          North Carolina
34            North Dakota
35                    Ohio
36                Oklahoma
37                  Oregon
38            Pennsylvania
39            Rhode Island
40          South Carolina
41            South Dakota
42               Tennessee
43                   Texas
44                    Utah
45                 Vermont
46                Virginia
47              Washington
48           West Virginia
49               Wisconsin
50                 Wyoming
Name: state, dtype: object

In [16]:
COVIDCases = COVIDCases.rename(columns = {'state':'State'})
COVIDCases.head()

        State  fips    cases  deaths
0     Alabama    73   387786   14345
1      Alaska   148    18316     367
2     Arizona   480   426614   18857
3    Arkansas   375   161569    3301
4  California   726  2664110  102387

In [17]:
COVIDHealthPerStateCapita = pd.merge(COVIDCases, PerStateCapitaFinal, how = 'left', on = 'State')
COVIDHealthPerStateCapita

,State,fips,cases,deaths,Personal Health Care Expenses Per State Capita (2014),Hospital Services Expenses Per State Capita (2014),Physician and Clinical Services Expenses Per State Capita (2014),Other Professional Services Expenses Per State Capita (2014),Home Health Care Expenses Per State Capita (2014),Drugs and Non-Durables Expenses Per State Capita (2014),Durables Expenses Per State Capita (2014),Other Health Care Expenses Per State Capita (2014)
0,Alabama,73,387786,14345,7281.0,2625.0,1739.0,170.0,202.0,1407.0,142.0,324.0
1,Alaska,148,18316,367,11064.0,4715.0,3368.0,465.0,195.0,640.0,139.0,797.0
2,Arizona,480,426614,18857,6452.0,2337.0,1774.0,248.0,136.0,814.0,175.0,347.0
3,Arkansas,375,161569,3301,7408.0,2673.0,1635.0,262.0,181.0,1169.0,104.0,635.0
4,California,726,2664110,102387,7549.0,2753.0,1983.0,217.0,291.0,955.0,97.0,495.0
5,Colorado,648,766512,37828,6804.0,2739.0,1602.0,325.0,192.0,681.0,172.0,290.0
6,Connecticut,702,1314995,104185,9859.0,3326.0,2186.0,322.0,296.0,1476.0,141.0,790.0
7,Delaware,750,234327,7813,10254.0,4078.0,2259.0,348.0,239.0,1525.0,197.0,591.0
8,District of Columbia,869,229466,10822,11944.0,5233.0,2457.0,223.0,653.0,1171.0,116.0,1098.0
9,Florida,1020,1726811,63147,8076.0,2732.0,2192.0,301.0,294.0,1232.0,253.0,254.0
10,Georgia,1092,1282091,54209,6587.0,2446.0,1817.0,211.0,163.0,938.0,140.0,259.0
11,Hawaii,1200,31433,681,7299.0,2764.0,1922.0,233.0,163.0,1181.0,170.0,174.0
12,Idaho,1168,103987,2828,6927.0,3038.0,1325.0,302.0,178.0,796.0,149.0,383.0
13,Illinois,2074,2843621,122000,8262.0,3380.0,1876.0,339.0,218.0,1006.0,128.0,439.0
14,Indiana,1440,920434,53042,8300.0,3492.0,1841.0,242.0,162.0,1119.0,164.0,372.0
15,Iowa,1482,396980,9203,8200.0,3292.0,1553.0,262.0,176.0,1148.0,139.0,616.0
16,Kansas,1580,231885,6527,7651.0,2964.0,1702.0,267.0,138.0,1119.0,125.0,417.0
17,Kentucky,1680,246480,11851,8004.0,3217.0,1830.0,228.0,160.0,1199.0,149.0,477.0
18,Louisiana,1694,1443404,90609,7815.0,3050.0,1719.0,238.0,283.0,1257.0,101.0,479.0
19,Maine,1702,61284,2451,9531.0,3953.0,1684.0,329.0,203.0,1159.0,137.0,1100.0
20,Maryland,1944,1173802,56126,8602.0,3283.0,2113.0,276.0,177.0,1147.0,126.0,482.0
21,Massachusetts,2850,2929874,167711,10559.0,3933.0,2264.0,301.0,667.0,1250.0,170.0,774.0
22,Michigan,1976,2023047,171867,8055.0,3256.0,1738.0,265.0,288.0,1106.0,273.0,273.0
23,Minnesota,2160,377850,18934,8871.0,3373.0,1759.0,270.0,524.0,955.0,135.0,867.0
24,Mississippi,2100,358459,15047,7646.0,3228.0,1565.0,190.0,212.0,1132.0,165.0,452.0
25,Missouri,2291,395952,17924,8107.0,3492.0,1542.0,228.0,227.0,1273.0,107.0,413.0
26,Montana,2190,23875,676,8221.0,3722.0,1658.0,303.0,151.0,865.0,165.0,546.0
27,Nebraska,3038,259429,3535,8412.0,3492.0,1758.0,296.0,97.0,1242.0,185.0,412.0
28,Nevada,2592,259808,11975,6714.0,2376.0,1872.0,273.0,233.0,966.0,150.0,244.0
29,New Hampshire,2772,117245,4507,9589.0,3771.0,2227.0,263.0,228.0,1222.0,191.0,571.0
30,New Jersey,2788,5645458,332869,8859.0,2915.0,2369.0,361.0,244.0,1355.0,159.0,478.0
31,New Mexico,2625,177827,6867,7214.0,3166.0,1591.0,268.0,250.0,748.0,207.0,354.0
32,New York,3060,15041806,1081194,9778.0,3633.0,1873.0,299.0,478.0,1435.0,144.0,936.0
33,North Carolina,3071,568719,19258,7264.0,2779.0,1612.0,221.0,195.0,1238.0,142.0,267.0
34,North Dakota,2850,55932,1219,9851.0,4479.0,1713.0,260.0,72.0,1175.0,165.0,811.0
35,Ohio,3003,908834,47879,8712.0,3809.0,1779.0,233.0,259.0,1023.0,144.0,542.0
36,Oklahoma,3200,187462,10394,7627.0,3118.0,1651.0,260.0,195.0,1180.0,115.0,359.0
37,Oregon,3567,134979,5067,8044.0,2940.0,1879.0,330.0,167.0,882.0,129.0,793.0
38,Pennsylvania,3360,2320771,127278,9258.0,3416.0,1967.0,308.0,244.0,1345.0,141.0,747.0
39,Rhode Island,3740,401931,14251,9551.0,3617.0,1855.0,311.0,252.0,1411.0,138.0,888.0
40,South Carolina,3600,313173,11859,7311.0,2933.0,1618.0,204.0,219.0,1193.0,154.0,288.0
41,South Dakota,3496,122292,1121,8933.0,4415.0,1635.0,256.0,93.0,949.0,126.0,468.0
42,Tennessee,3807,583792,10198,7372.0,2617.0,1880.0,219.0,214.0,1216.0,136.0,391.0
43,Texas,4944,1553075,41267,6998.0,2698.0,1695.0,208.0,282.0,1073.0,115.0,333.0
44,Utah,4410,245859,2472,5982.0,2351.0,1319.0,212.0,188.0,784.0,161.0,361.0
45,Vermont,3950,45230,2320,10190.0,4670.0,1750.0,321.0,301.0,1158.0,129.0,837.0
46,Virginia,4029,866807,28754,7556.0,2912.0,1877.0,225.0,152.0,1015.0,135.0,420.0
47,Washington,6625,807848,42371,7913.0,3090.0,2064.0,324.0,188.0,795.0,146.0,346.0
48,West Virginia,3726,56158,1950,9462.0,4037.0,1807.0,238.0,272.0,1377.0,186.0,710.0
49,Wisconsin,6050,393823,15587,8702.0,3502.0,2168.0,264.0,230.0,1103.0,125.0,363.0
50,Wyoming,4200,28407,281,8320.0,4001.0,1771.0,377.0,77.0,751.0,129.0,416.0

In [18]:
COVIDHealthPerStateCapita = COVIDHealthPerStateCapita.drop(['fips'], axis = 1)
COVIDHealthPerStateCapita

,State,cases,deaths,Personal Health Care Expenses Per State Capita (2014),Hospital Services Expenses Per State Capita (2014),Physician and Clinical Services Expenses Per State Capita (2014),Other Professional Services Expenses Per State Capita (2014),Home Health Care Expenses Per State Capita (2014),Drugs and Non-Durables Expenses Per State Capita (2014),Durables Expenses Per State Capita (2014),Other Health Care Expenses Per State Capita (2014)
0,Alabama,387786,14345,7281.0,2625.0,1739.0,170.0,202.0,1407.0,142.0,324.0
1,Alaska,18316,367,11064.0,4715.0,3368.0,465.0,195.0,640.0,139.0,797.0
2,Arizona,426614,18857,6452.0,2337.0,1774.0,248.0,136.0,814.0,175.0,347.0
3,Arkansas,161569,3301,7408.0,2673.0,1635.0,262.0,181.0,1169.0,104.0,635.0
4,California,2664110,102387,7549.0,2753.0,1983.0,217.0,291.0,955.0,97.0,495.0
5,Colorado,766512,37828,6804.0,2739.0,1602.0,325.0,192.0,681.0,172.0,290.0
6,Connecticut,1314995,104185,9859.0,3326.0,2186.0,322.0,296.0,1476.0,141.0,790.0
7,Delaware,234327,7813,10254.0,4078.0,2259.0,348.0,239.0,1525.0,197.0,591.0
8,District of Columbia,229466,10822,11944.0,5233.0,2457.0,223.0,653.0,1171.0,116.0,1098.0
9,Florida,1726811,63147,8076.0,2732.0,2192.0,301.0,294.0,1232.0,253.0,254.0
10,Georgia,1282091,54209,6587.0,2446.0,1817.0,211.0,163.0,938.0,140.0,259.0
11,Hawaii,31433,681,7299.0,2764.0,1922.0,233.0,163.0,1181.0,170.0,174.0
12,Idaho,103987,2828,6927.0,3038.0,1325.0,302.0,178.0,796.0,149.0,383.0
13,Illinois,2843621,122000,8262.0,3380.0,1876.0,339.0,218.0,1006.0,128.0,439.0
14,Indiana,920434,53042,8300.0,3492.0,1841.0,242.0,162.0,1119.0,164.0,372.0
15,Iowa,396980,9203,8200.0,3292.0,1553.0,262.0,176.0,1148.0,139.0,616.0
16,Kansas,231885,6527,7651.0,2964.0,1702.0,267.0,138.0,1119.0,125.0,417.0
17,Kentucky,246480,11851,8004.0,3217.0,1830.0,228.0,160.0,1199.0,149.0,477.0
18,Louisiana,1443404,90609,7815.0,3050.0,1719.0,238.0,283.0,1257.0,101.0,479.0
19,Maine,61284,2451,9531.0,3953.0,1684.0,329.0,203.0,1159.0,137.0,1100.0
20,Maryland,1173802,56126,8602.0,3283.0,2113.0,276.0,177.0,1147.0,126.0,482.0
21,Massachusetts,2929874,167711,10559.0,3933.0,2264.0,301.0,667.0,1250.0,170.0,774.0
22,Michigan,2023047,171867,8055.0,3256.0,1738.0,265.0,288.0,1106.0,273.0,273.0
23,Minnesota,377850,18934,8871.0,3373.0,1759.0,270.0,524.0,955.0,135.0,867.0
24,Mississippi,358459,15047,7646.0,3228.0,1565.0,190.0,212.0,1132.0,165.0,452.0
25,Missouri,395952,17924,8107.0,3492.0,1542.0,228.0,227.0,1273.0,107.0,413.0
26,Montana,23875,676,8221.0,3722.0,1658.0,303.0,151.0,865.0,165.0,546.0
27,Nebraska,259429,3535,8412.0,3492.0,1758.0,296.0,97.0,1242.0,185.0,412.0
28,Nevada,259808,11975,6714.0,2376.0,1872.0,273.0,233.0,966.0,150.0,244.0
29,New Hampshire,117245,4507,9589.0,3771.0,2227.0,263.0,228.0,1222.0,191.0,571.0
30,New Jersey,5645458,332869,8859.0,2915.0,2369.0,361.0,244.0,1355.0,159.0,478.0
31,New Mexico,177827,6867,7214.0,3166.0,1591.0,268.0,250.0,748.0,207.0,354.0
32,New York,15041806,1081194,9778.0,3633.0,1873.0,299.0,478.0,1435.0,144.0,936.0
33,North Carolina,568719,19258,7264.0,2779.0,1612.0,221.0,195.0,1238.0,142.0,267.0
34,North Dakota,55932,1219,9851.0,4479.0,1713.0,260.0,72.0,1175.0,165.0,811.0
35,Ohio,908834,47879,8712.0,3809.0,1779.0,233.0,259.0,1023.0,144.0,542.0
36,Oklahoma,187462,10394,7627.0,3118.0,1651.0,260.0,195.0,1180.0,115.0,359.0
37,Oregon,134979,5067,8044.0,2940.0,1879.0,330.0,167.0,882.0,129.0,793.0
38,Pennsylvania,2320771,127278,9258.0,3416.0,1967.0,308.0,244.0,1345.0,141.0,747.0
39,Rhode Island,401931,14251,9551.0,3617.0,1855.0,311.0,252.0,1411.0,138.0,888.0
40,South Carolina,313173,11859,7311.0,2933.0,1618.0,204.0,219.0,1193.0,154.0,288.0
41,South Dakota,122292,1121,8933.0,4415.0,1635.0,256.0,93.0,949.0,126.0,468.0
42,Tennessee,583792,10198,7372.0,2617.0,1880.0,219.0,214.0,1216.0,136.0,391.0
43,Texas,1553075,41267,6998.0,2698.0,1695.0,208.0,282.0,1073.0,115.0,333.0
44,Utah,245859,2472,5982.0,2351.0,1319.0,212.0,188.0,784.0,161.0,361.0
45,Vermont,45230,2320,10190.0,4670.0,1750.0,321.0,301.0,1158.0,129.0,837.0
46,Virginia,866807,28754,7556.0,2912.0,1877.0,225.0,152.0,1015.0,135.0,420.0
47,Washington,807848,42371,7913.0,3090.0,2064.0,324.0,188.0,795.0,146.0,346.0
48,West Virginia,56158,1950,9462.0,4037.0,1807.0,238.0,272.0,1377.0,186.0,710.0
49,Wisconsin,393823,15587,8702.0,3502.0,2168.0,264.0,230.0,1103.0,125.0,363.0
50,Wyoming,28407,281,8320.0,4001.0,1771.0,377.0,77.0,751.0,129.0,416.0