In [20]:
import pandas as pd
import numpy as np
from functools import reduce

In [21]:
PhiSci = pd.read_excel('physical-scientists-to-all-occupations.xlsx')
PhiSci

,Table S-36,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
0,Physical Scientists as a Percentage of All Occ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Physical scientists,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,2003,2004.0,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,...,2009.000000,2010.000000,2011.000000,2012.000000,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000
3,United States,271030,278750.0,280810.0,291380.0,297640.0,301500.0,302980.0,305360.0,309320.0,...,0.231906,0.240257,0.241132,0.245464,0.243052,0.237574,0.226771,0.220014,0.209892,0.207907
4,Alabama,3470,3270.0,3410.0,2880.0,3050.0,3110.0,NaN,NaN,3030.0,...,NaN,NaN,0.167457,0.175948,0.171359,NaN,0.163011,0.166232,0.149279,0.143022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,NOTES: Occupational Employment Statistics (OES...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,"SOURCE: Bureau of Labor Statistics, special ta...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,Recommended Citation: National Science Board. ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,"Last updated: September 24, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Science and Engineering Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
PhiSci2 = PhiSci.drop(['Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
                          'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
                          'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32',
                          'Unnamed: 34', 'Unnamed: 33', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
                          'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45',
                          'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50'], axis = 1)

PhiSci2.head()

,Table S-36,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Physical Scientists as a Percentage of All Occ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Physical scientists,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,2003,2004.0,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0
3,United States,271030,278750.0,280810.0,291380.0,297640.0,301500.0,302980.0,305360.0,309320.0,319810.0,322260.0,321030.0,312710.0,308900.0,299200.0,300910.0
4,Alabama,3470,3270.0,3410.0,2880.0,3050.0,3110.0,NaN,NaN,3030.0,3210.0,3160.0,NaN,3070.0,3180.0,2870.0,2780.0

In [23]:
PhiSci2.drop(range(0,4), inplace = True)
PhiSci2.drop(range(55,64), inplace = True)
PhiSci2 = PhiSci2.reset_index(drop = True)
PhiSci2

,Table S-36,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Alabama,3470,3270.0,3410.0,2880.0,3050.0,3110.0,NaN,NaN,3030.0,3210.0,3160.0,NaN,3070.0,3180.0,2870.0,2780.0
1,Alaska,1370,1350.0,1340.0,1150.0,1400.0,1600.0,1790.0,1770.0,1880.0,2160.0,2240.0,2130.0,1930.0,1690.0,1680.0,1670.0
2,Arizona,3860,4170.0,4100.0,3670.0,3960.0,4070.0,NaN,NaN,NaN,4430.0,4950.0,NaN,4240.0,4020.0,4130.0,NaN
3,Arkansas,1420,1710.0,1570.0,1390.0,1790.0,1140.0,1430.0,1420.0,NaN,1510.0,1350.0,1310.0,NaN,NaN,NaN,NaN
4,California,32030,32440.0,32780.0,NaN,NaN,NaN,39960.0,40530.0,41230.0,43200.0,46700.0,47060.0,44450.0,42860.0,38970.0,39360.0
5,Colorado,7550,7840.0,8910.0,9520.0,9990.0,9920.0,NaN,NaN,10650.0,NaN,11480.0,11740.0,11840.0,12080.0,11170.0,NaN
6,Connecticut,3500,3700.0,3590.0,2920.0,2710.0,NaN,2980.0,3510.0,3930.0,4210.0,NaN,3450.0,3100.0,NaN,2930.0,3320.0
7,Delaware,1980,1830.0,2040.0,1550.0,1690.0,1770.0,2730.0,2610.0,2950.0,3960.0,4210.0,4220.0,NaN,NaN,NaN,2230.0
8,District of Columbia,3330,3420.0,3680.0,3910.0,3970.0,3760.0,3580.0,3570.0,3630.0,3500.0,3420.0,3390.0,3320.0,3330.0,3370.0,3570.0
9,Florida,11290,11920.0,12090.0,12590.0,12200.0,12010.0,12950.0,13200.0,NaN,12260.0,11640.0,11490.0,11710.0,11770.0,11490.0,10840.0
10,Georgia,5020,5670.0,4880.0,4470.0,3930.0,4870.0,5510.0,5560.0,5700.0,5590.0,5240.0,4990.0,4910.0,NaN,NaN,NaN
11,Hawaii,1310,1450.0,1420.0,1610.0,1760.0,1680.0,1710.0,1670.0,1590.0,1660.0,1620.0,1580.0,1500.0,1560.0,1580.0,1630.0
12,Idaho,1570,1680.0,1700.0,1600.0,1160.0,1340.0,1420.0,1550.0,1660.0,1750.0,2130.0,2150.0,2110.0,1780.0,1730.0,1840.0
13,Illinois,9970,10340.0,11090.0,13180.0,12150.0,12190.0,10880.0,11230.0,10050.0,10980.0,9960.0,9460.0,9790.0,9590.0,9640.0,NaN
14,Indiana,4080,4390.0,4740.0,NaN,5090.0,5800.0,5520.0,5580.0,6220.0,6100.0,6200.0,NaN,5180.0,NaN,NaN,5850.0
15,Iowa,1690,NaN,NaN,1830.0,1430.0,1570.0,1490.0,1460.0,1460.0,1840.0,1870.0,1910.0,1860.0,1700.0,1620.0,1670.0
16,Kansas,2080,2060.0,2170.0,2410.0,2300.0,2670.0,2590.0,2580.0,2440.0,2390.0,2500.0,2260.0,2140.0,1850.0,2170.0,2280.0
17,Kentucky,2210,2200.0,NaN,2270.0,2430.0,NaN,2600.0,2680.0,2530.0,2400.0,2260.0,2370.0,2830.0,2860.0,2600.0,2540.0
18,Louisiana,4180,4350.0,4210.0,4040.0,3770.0,3580.0,3850.0,3840.0,3810.0,3800.0,3660.0,3530.0,3520.0,3680.0,3320.0,3370.0
19,Maine,1200,1300.0,1270.0,1490.0,1530.0,1530.0,1380.0,1360.0,1350.0,NaN,1210.0,1300.0,1230.0,1250.0,NaN,1300.0
20,Maryland,NaN,9410.0,9660.0,9630.0,10470.0,11630.0,10990.0,NaN,NaN,12210.0,11960.0,11620.0,NaN,10550.0,NaN,NaN
21,Massachusetts,9060,9150.0,8960.0,9230.0,9710.0,NaN,9360.0,NaN,NaN,NaN,10450.0,9560.0,NaN,8250.0,NaN,NaN
22,Michigan,NaN,6640.0,6400.0,NaN,6410.0,6970.0,7000.0,6880.0,NaN,7270.0,7360.0,9180.0,8810.0,9180.0,8280.0,9390.0
23,Minnesota,4670,4840.0,4780.0,5790.0,5590.0,5480.0,5280.0,5470.0,NaN,5220.0,NaN,5610.0,NaN,NaN,5570.0,6130.0
24,Mississippi,1930,1910.0,1970.0,2100.0,2030.0,2160.0,2220.0,NaN,NaN,2150.0,2060.0,1940.0,1820.0,1670.0,1790.0,1740.0
25,Missouri,4490,4730.0,4730.0,4510.0,NaN,NaN,NaN,4660.0,NaN,4700.0,5160.0,5130.0,4870.0,4260.0,NaN,NaN
26,Montana,1060,1220.0,1280.0,1460.0,NaN,NaN,1440.0,1390.0,1310.0,1310.0,1420.0,1440.0,1460.0,1220.0,1330.0,1460.0
27,Nebraska,1740,1670.0,1630.0,1660.0,1350.0,1470.0,1510.0,1580.0,1700.0,1830.0,1990.0,1880.0,1620.0,1660.0,1350.0,1250.0
28,Nevada,2010,2060.0,2100.0,2370.0,2230.0,2250.0,2380.0,2410.0,2650.0,2550.0,2620.0,2450.0,2730.0,2500.0,NaN,2210.0
29,New Hampshire,1110,1280.0,1350.0,1340.0,1350.0,1370.0,1260.0,1240.0,1250.0,1290.0,1380.0,1470.0,1450.0,1460.0,1430.0,1350.0
30,New Jersey,11730,11490.0,10120.0,NaN,12490.0,13620.0,11510.0,11610.0,11430.0,11950.0,11220.0,10690.0,10880.0,12490.0,13000.0,13130.0
31,New Mexico,NaN,NaN,NaN,3380.0,5370.0,5130.0,5420.0,4700.0,5230.0,5050.0,4800.0,NaN,4970.0,NaN,4560.0,4640.0
32,New York,NaN,14870.0,14780.0,16970.0,17130.0,14470.0,13690.0,NaN,NaN,NaN,NaN,NaN,NaN,16410.0,15980.0,15850.0
33,North Carolina,NaN,NaN,9750.0,9700.0,NaN,10300.0,10240.0,10580.0,10120.0,11600.0,11360.0,11230.0,10780.0,11030.0,11710.0,11590.0
34,North Dakota,540,470.0,510.0,510.0,570.0,560.0,600.0,540.0,590.0,920.0,950.0,880.0,810.0,890.0,860.0,850.0
35,Ohio,NaN,10150.0,9860.0,10820.0,11090.0,10800.0,9610.0,10280.0,NaN,10860.0,NaN,10930.0,11440.0,NaN,10720.0,10000.0
36,Oklahoma,2680,3330.0,3480.0,3820.0,3750.0,2930.0,2870.0,3050.0,3000.0,3860.0,3440.0,3130.0,2750.0,NaN,2710.0,3010.0
37,Oregon,2570,2720.0,2730.0,NaN,2880.0,3140.0,3030.0,NaN,3570.0,3890.0,3740.0,3380.0,3280.0,3010.0,3450.0,3430.0
38,Pennsylvania,11800,10680.0,10750.0,11440.0,10940.0,11460.0,11340.0,12040.0,12290.0,NaN,14290.0,NaN,NaN,13230.0,12860.0,13000.0
39,Rhode Island,1570,1690.0,1550.0,1030.0,970.0,1030.0,1160.0,1040.0,1080.0,950.0,890.0,920.0,940.0,940.0,970.0,920.0
40,South Carolina,2750,3270.0,3280.0,3320.0,3180.0,3130.0,3350.0,3130.0,NaN,NaN,NaN,2940.0,2430.0,2660.0,2840.0,2930.0
41,South Dakota,560,560.0,550.0,610.0,NaN,750.0,680.0,650.0,710.0,NaN,780.0,800.0,770.0,780.0,690.0,720.0
42,Tennessee,4420,4440.0,NaN,5060.0,5280.0,5020.0,3990.0,3950.0,NaN,NaN,4510.0,4090.0,4430.0,4030.0,4330.0,4470.0
43,Texas,20710,21510.0,22010.0,23590.0,NaN,24680.0,29510.0,NaN,NaN,29050.0,NaN,29880.0,28340.0,28260.0,25060.0,25120.0
44,Utah,2690,2690.0,2820.0,3030.0,2790.0,2940.0,2860.0,2940.0,NaN,NaN,2660.0,2640.0,2740.0,2770.0,2980.0,NaN
45,Vermont,530,580.0,570.0,560.0,630.0,630.0,760.0,680.0,970.0,920.0,970.0,800.0,870.0,920.0,940.0,820.0
46,Virginia,NaN,NaN,8790.0,9260.0,9210.0,8890.0,9190.0,NaN,9190.0,9180.0,NaN,NaN,NaN,8890.0,9440.0,9670.0
47,Washington,7590,NaN,NaN,NaN,NaN,NaN,NaN,9800.0,10330.0,9810.0,10060.0,9490.0,10060.0,9220.0,9220.0,8580.0
48,West Virginia,1680,1870.0,1970.0,1860.0,1750.0,1680.0,1600.0,1410.0,1280.0,1540.0,1460.0,1310.0,1280.0,1170.0,1400.0,1610.0
49,Wisconsin,5130,5490.0,5820.0,6130.0,6570.0,5950.0,6090.0,5300.0,5530.0,4370.0,4360.0,4290.0,5410.0,5420.0,5100.0,4290.0
50,Wyoming,760,900.0,1060.0,1000.0,1150.0,1150.0,1070.0,970.0,950.0,1110.0,1130.0,1110.0,1090.0,1020.0,960.0,1010.0

In [24]:
m = PhiSci2.mean(axis=1)
for i, col in enumerate(PhiSci2):
    PhiSci2.iloc[:, i] = PhiSci2.iloc[:, i].fillna(m)
PhiSci2 = PhiSci2.drop(['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
                          'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
                          'Unnamed: 14', 'Unnamed: 15'], axis = 1)

PhiSci2 = PhiSci2.rename(columns = {'Table S-36':'State',
                                       'Unnamed: 16':'Physical Scientists 2018'})

PhiSci2.head(10)

                  State  Physical Scientists 2018
0               Alabama               2780.000000
1                Alaska               1670.000000
2               Arizona               4174.000000
3              Arkansas               1462.000000
4            California              39360.000000
5              Colorado              10467.272727
6           Connecticut               3320.000000
7              Delaware               2230.000000
8  District of Columbia               3570.000000
9               Florida              10840.000000

In [25]:
PhiSci3 = PhiSci.drop(['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
                          'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
                          'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
                          'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45',
                          'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50'], axis = 1)

PhiSci3.head()

,Table S-36,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,Physical Scientists as a Percentage of All Occ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,All occupations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,2003,2004.0,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0
3,United States,127420170,129146700.0,130307840.0,132604980.0,134354250.0,135185230.0,130647610.0,127097160.0,128278550.0,130287700.0,132588810.0,135128260.0,137896660.0,140400040.0,142549250.0,144733270.0
4,Alabama,1817240,1851040.0,1872600.0,1912220.0,1931970.0,1945300.0,1863620.0,1807480.0,1809420.0,1824400.0,1844080.0,1857530.0,1883310.0,1912990.0,1922570.0,1943760.0

In [26]:
PhiSci3.drop(range(0,4), inplace = True)
PhiSci3.drop(range(55,64), inplace = True)
PhiSci3 = PhiSci3.reset_index(drop = True)
PhiSci3

,Table S-36,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,Alabama,1817240,1851040.0,1872600.0,1912220.0,1931970.0,1945300.0,1863620.0,1807480.0,1809420.0,1824400.0,1844080.0,1857530.0,1883310.0,1912990.0,1922570.0,1943760.0
1,Alaska,290740,295810.0,300150.0,303890.0,301920.0,307790.0,308140.0,308050.0,313170.0,318700.0,322660.0,324970.0,327250.0,323500.0,318170.0,315250.0
2,Arizona,2275410,2370810.0,2437100.0,2574150.0,2648000.0,2637830.0,2479120.0,2367120.0,2380200.0,2414340.0,2475660.0,2526990.0,2587070.0,2652990.0,2704050.0,2789520.0
3,Arkansas,1118690,1133800.0,1142370.0,1166840.0,1172760.0,1176050.0,1147660.0,1135560.0,1139670.0,1155020.0,1152600.0,1158790.0,1176130.0,1191320.0,1200130.0,1210120.0
4,California,14460860,14598250.0,14723900.0,15065750.0,15202530.0,15212610.0,14532640.0,14001730.0,14038950.0,14303630.0,14714530.0,15119730.0,15496600.0,15966580.0,16695010.0,17007690.0
5,Colorado,2097650,2130430.0,2151520.0,2207120.0,2258240.0,2302340.0,2234250.0,2157690.0,2179060.0,2226160.0,2295000.0,2367780.0,2451490.0,2507680.0,2555300.0,2620640.0
6,Connecticut,1631610,1640840.0,1648070.0,1658980.0,1682220.0,1697810.0,1648950.0,1598640.0,1608820.0,1620620.0,1635590.0,1646510.0,1659430.0,1666280.0,1654420.0,1660200.0
7,Delaware,403650,413940.0,417550.0,424270.0,425960.0,425210.0,412570.0,397730.0,403430.0,405750.0,412140.0,424330.0,433840.0,440760.0,442690.0,448510.0
8,District of Columbia,595220,609770.0,611190.0,609400.0,620970.0,635500.0,637180.0,639390.0,644730.0,653760.0,665850.0,674650.0,676060.0,702380.0,708220.0,712370.0
9,Florida,7217400,7479050.0,7614840.0,7869210.0,7963010.0,7771740.0,7355940.0,7103950.0,7151700.0,7273850.0,7453230.0,7665280.0,7925300.0,8222030.0,8419030.0,8608660.0
10,Georgia,3770430,3848740.0,3904020.0,4001580.0,4058370.0,4068270.0,3889160.0,3744740.0,3779250.0,3815530.0,3879660.0,3983250.0,4107960.0,4214410.0,4303530.0,4394740.0
11,Hawaii,557400,573890.0,583630.0,599130.0,610310.0,612420.0,587810.0,571630.0,577220.0,588210.0,602200.0,612580.0,619960.0,632120.0,632990.0,641790.0
12,Idaho,563200,584580.0,597490.0,624320.0,641960.0,650240.0,614520.0,594750.0,592730.0,598540.0,613000.0,628140.0,642700.0,663490.0,685630.0,706140.0
13,Illinois,5719150,5739250.0,5767100.0,5826660.0,5894670.0,5910630.0,5704240.0,5528420.0,5574180.0,5640740.0,5704700.0,5765880.0,5852710.0,5903820.0,5927860.0,5991270.0
14,Indiana,2851210,2879070.0,2891360.0,2913200.0,2928780.0,2927620.0,2787780.0,2724850.0,2758100.0,2811920.0,2854250.0,2905170.0,2947380.0,2991260.0,3018490.0,3048100.0
15,Iowa,1413220,1433570.0,1446550.0,1470240.0,1488360.0,1502600.0,1471130.0,1438510.0,1449110.0,1470740.0,1491600.0,1512740.0,1526950.0,1534910.0,1535460.0,1541700.0
16,Kansas,1292170,1311390.0,1315640.0,1321180.0,1347670.0,1374560.0,1348710.0,1304780.0,1308070.0,1320920.0,1336460.0,1359500.0,1371630.0,1374180.0,1369110.0,1375380.0
17,Kentucky,1719620,1736230.0,1754590.0,1779830.0,1801800.0,1817860.0,1748610.0,1716060.0,1732870.0,1764750.0,1782820.0,1808010.0,1838220.0,1869650.0,1876430.0,1889870.0
18,Louisiana,1851870,1865300.0,1877160.0,1776990.0,1847230.0,1887370.0,1871950.0,1832830.0,1839780.0,1868210.0,1885310.0,1915800.0,1939300.0,1922170.0,1902060.0,1913770.0
19,Maine,591750,598350.0,597260.0,596910.0,600020.0,604150.0,589090.0,577410.0,575640.0,581110.0,582430.0,586390.0,591520.0,596390.0,599180.0,605550.0
20,Maryland,2448580,2477280.0,2497220.0,2531180.0,2551910.0,2561530.0,2503410.0,2462470.0,2480670.0,2510680.0,2534480.0,2557510.0,2596630.0,2640900.0,2664330.0,2684010.0
21,Massachusetts,3130720,3129090.0,3144540.0,3170490.0,3207840.0,3234860.0,3169010.0,3119100.0,3157020.0,3202080.0,3257870.0,3322500.0,3396840.0,3459910.0,3528070.0,3571360.0
22,Michigan,4310420,4324840.0,4334870.0,4294260.0,4210550.0,4142750.0,3893900.0,3755890.0,3829000.0,3918120.0,3998790.0,4073730.0,4146600.0,4212090.0,4276040.0,4317830.0
23,Minnesota,2591720,2625060.0,2635370.0,2682940.0,2687740.0,2704860.0,2627640.0,2562450.0,2595450.0,2641110.0,2688580.0,2730020.0,2772240.0,2810400.0,2838270.0,2867700.0
24,Mississippi,1089350,1101680.0,1108540.0,1113000.0,1128980.0,1138210.0,1096890.0,1070820.0,1073100.0,1080420.0,1083560.0,1094070.0,1106550.0,1117280.0,1119470.0,1123830.0
25,Missouri,2623020,2646990.0,2663880.0,2700450.0,2732920.0,2740170.0,2668450.0,2588450.0,2591020.0,2605910.0,2639120.0,2673640.0,2712240.0,2757850.0,2788680.0,2804780.0
26,Montana,394820,408730.0,414650.0,427130.0,435480.0,444090.0,432240.0,424300.0,425110.0,432380.0,439110.0,443330.0,447180.0,454740.0,460740.0,463280.0
27,Nebraska,879550,887200.0,895470.0,901120.0,914670.0,928120.0,916770.0,901690.0,904630.0,914830.0,927150.0,942950.0,953710.0,968000.0,970230.0,978290.0
28,Nevada,1086110,1154440.0,1191640.0,1257860.0,1285470.0,1278230.0,1179860.0,1113530.0,1112780.0,1127160.0,1151970.0,1189610.0,1232800.0,1270930.0,1310220.0,1347130.0
29,New Hampshire,607570,618310.0,621560.0,627570.0,632590.0,634570.0,619390.0,603420.0,606690.0,612710.0,620190.0,627000.0,635360.0,645050.0,649950.0,652920.0
30,New Jersey,3878020,3901020.0,3917310.0,3957500.0,3980080.0,3986310.0,3850770.0,3770550.0,3771250.0,3793720.0,3821070.0,3869260.0,3906800.0,3955350.0,4007470.0,4050170.0
31,New Mexico,747050,754990.0,763430.0,789360.0,798640.0,819480.0,800390.0,777560.0,777640.0,773860.0,783980.0,788000.0,798150.0,805440.0,801080.0,811680.0
32,New York,8236200,8299910.0,8333460.0,8387750.0,8515960.0,8633580.0,8487020.0,8344020.0,8427560.0,8542280.0,8635400.0,8810950.0,8984890.0,9097650.0,9207870.0,9385620.0
33,North Carolina,3702170,3770700.0,3809690.0,3892670.0,4013460.0,4063420.0,3896750.0,3772780.0,3814860.0,3878800.0,3947030.0,4030880.0,4125070.0,4231020.0,4298390.0,4383210.0
34,North Dakota,314620,324430.0,328520.0,335740.0,341970.0,350360.0,353630.0,355710.0,371630.0,403290.0,422930.0,440420.0,447820.0,425200.0,416670.0,416550.0
35,Ohio,5308270,5324700.0,5340280.0,5354170.0,5341360.0,5323130.0,5091490.0,4921690.0,4977910.0,5054250.0,5125850.0,5200880.0,5280850.0,5337890.0,5370640.0,5416810.0
36,Oklahoma,1416640,1436380.0,1455940.0,1503430.0,1528890.0,1557750.0,1525330.0,1483760.0,1498260.0,1529900.0,1558860.0,1577330.0,1597130.0,1586890.0,1573000.0,1594370.0
37,Oregon,1537000,1576890.0,1598780.0,1648680.0,1682150.0,1706740.0,1624490.0,1569700.0,1586620.0,1609900.0,1640300.0,1683470.0,1735220.0,1790940.0,1830790.0,1886090.0
38,Pennsylvania,5494430,5535000.0,5569310.0,5631520.0,5663070.0,5705170.0,5572660.0,5483220.0,5549240.0,5596480.0,5616820.0,5653840.0,5709480.0,5747020.0,5781610.0,5847690.0
39,Rhode Island,477320,480290.0,479810.0,482550.0,485870.0,478420.0,458760.0,448150.0,450980.0,453020.0,456100.0,463930.0,471290.0,475190.0,475910.0,482030.0
40,South Carolina,1764170,1792190.0,1802740.0,1840190.0,1877950.0,1892690.0,1802900.0,1746820.0,1772880.0,1796550.0,1826120.0,1876480.0,1928140.0,1979820.0,2009460.0,2062280.0
41,South Dakota,364970,371010.0,373500.0,381230.0,389400.0,395960.0,392890.0,387590.0,392670.0,398680.0,402990.0,409250.0,413260.0,417520.0,419470.0,422310.0
42,Tennessee,2614830,2665060.0,2686580.0,2718410.0,2739230.0,2755800.0,2625140.0,2569420.0,2602320.0,2657280.0,2700050.0,2749480.0,2814230.0,2893040.0,2915750.0,2956920.0
43,Texas,9248660,9306600.0,9424510.0,9760960.0,10061750.0,10391420.0,10289240.0,10089870.0,10304370.0,10579400.0,10913950.0,11228940.0,11572540.0,11745250.0,11890880.0,12113810.0
44,Utah,1043500,1077210.0,1099230.0,1151020.0,1206180.0,1230320.0,1185770.0,1148520.0,1165980.0,1200850.0,1242690.0,1280660.0,1324460.0,1374900.0,1410670.0,1455910.0
45,Vermont,291400,296260.0,297650.0,299610.0,301140.0,301130.0,294120.0,286990.0,290830.0,294090.0,298290.0,301050.0,303550.0,304670.0,305110.0,305210.0
46,Virginia,3412070,3494250.0,3535500.0,3608430.0,3645330.0,3670980.0,3589520.0,3527350.0,3553360.0,3597100.0,3631440.0,3648490.0,3682450.0,3760550.0,3789910.0,3832840.0
47,Washington,2560190,2614640.0,2653320.0,2736910.0,2811700.0,2868910.0,2789670.0,2693220.0,2720660.0,2764080.0,2827200.0,2898350.0,2983930.0,3067110.0,3186610.0,3259150.0
48,West Virginia,680200,692840.0,697390.0,710560.0,713230.0,717740.0,704310.0,688170.0,700250.0,710540.0,709430.0,707720.0,707000.0,697440.0,688530.0,696620.0
49,Wisconsin,2687400,2717970.0,2727430.0,2744210.0,2768830.0,2776690.0,2689710.0,2608740.0,2645180.0,2673280.0,2704840.0,2727860.0,2771600.0,2805010.0,2825170.0,2848560.0
50,Wyoming,240730,246670.0,251590.0,262260.0,273170.0,283980.0,282450.0,269910.0,272570.0,278040.0,278910.0,282690.0,283830.0,276120.0,267980.0,269320.0

In [27]:
m = PhiSci3.mean(axis=1)
for i, col in enumerate(PhiSci3):
    PhiSci3.iloc[:, i] = PhiSci3.iloc[:, i].fillna(m)
PhiSci3 = PhiSci3.drop(['Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
                          'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
                          'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32',], axis = 1)

PhiSci3 = PhiSci3.rename(columns = {'Table S-36':'State',
                                       'Unnamed: 33':'All Occupations 2018'})

PhiSci3.head(10)

                  State  All Occupations 2018
0               Alabama             1943760.0
1                Alaska              315250.0
2               Arizona             2789520.0
3              Arkansas             1210120.0
4            California            17007690.0
5              Colorado             2620640.0
6           Connecticut             1660200.0
7              Delaware              448510.0
8  District of Columbia              712370.0
9               Florida             8608660.0

In [28]:
PhiSci4 = PhiSci.drop(['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
                          'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
                          'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
                          'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
                          'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
                          'Unnamed: 34',], axis = 1)

PhiSci4.head()

,Table S-36,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
0,Physical Scientists as a Percentage of All Occ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Physical scientists in all occupations (Percent),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,2003,2004.000000,2005.000000,2006.000000,2007.000000,2008.000000,2009.000000,2010.000000,2011.000000,2012.000000,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000
3,United States,0.212706,0.215840,0.215497,0.219735,0.221534,0.223027,0.231906,0.240257,0.241132,0.245464,0.243052,0.237574,0.226771,0.220014,0.209892,0.207907
4,Alabama,0.190949,0.176657,0.182100,0.150610,0.157870,0.159873,NaN,NaN,0.167457,0.175948,0.171359,NaN,0.163011,0.166232,0.149279,0.143022

In [29]:
PhiSci4.drop(range(0,4), inplace = True)
PhiSci4.drop(range(55,64), inplace = True)
PhiSci4 = PhiSci4.reset_index(drop = True)
PhiSci4

,Table S-36,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
0,Alabama,0.190949,0.176657,0.182100,0.150610,0.157870,0.159873,NaN,NaN,0.167457,0.175948,0.171359,NaN,0.163011,0.166232,0.149279,0.143022
1,Alaska,0.471211,0.456374,0.446443,0.378426,0.463699,0.519835,0.580905,0.574582,0.600313,0.677753,0.694229,0.655445,0.589763,0.522411,0.528020,0.529738
2,Arizona,0.16964,0.175889,0.168233,0.142571,0.149547,0.154293,NaN,NaN,NaN,0.183487,0.199947,NaN,0.163892,0.151527,0.152734,NaN
3,Arkansas,0.126934,0.150820,0.137434,0.119125,0.152631,0.096935,0.124601,0.125048,NaN,0.130734,0.117126,0.113049,NaN,NaN,NaN,NaN
4,California,0.221494,0.222218,0.222631,NaN,NaN,NaN,0.274967,0.289464,0.293683,0.302021,0.317373,0.311249,0.286837,0.268436,0.233423,0.231425
5,Colorado,0.359927,0.368001,0.414126,0.431331,0.442380,0.430866,NaN,NaN,0.488743,NaN,0.500218,0.495823,0.482972,0.481720,0.437131,NaN
6,Connecticut,0.214512,0.225494,0.217831,0.176012,0.161097,NaN,0.180721,0.219562,0.244278,0.259777,NaN,0.209534,0.186811,NaN,0.177101,0.199976
7,Delaware,0.490524,0.442093,0.488564,0.365333,0.396751,0.416265,0.661706,0.656224,0.731230,0.975970,1.021498,0.994509,NaN,NaN,NaN,0.497202
8,District of Columbia,0.559457,0.560867,0.602104,0.641615,0.639322,0.591660,0.561851,0.558345,0.563026,0.535365,0.513629,0.502483,0.491081,0.474102,0.475841,0.501144
9,Florida,0.156428,0.159379,0.158769,0.159991,0.153208,0.154534,0.176048,0.185812,NaN,0.168549,0.156174,0.149897,0.147755,0.143152,0.136477,0.125920
10,Georgia,0.133141,0.147321,0.124999,0.111706,0.096837,0.119707,0.141676,0.148475,0.150824,0.146507,0.135063,0.125275,0.119524,NaN,NaN,NaN
11,Hawaii,0.23502,0.252662,0.243305,0.268723,0.288378,0.274322,0.290910,0.292147,0.275458,0.282212,0.269014,0.257925,0.241951,0.246789,0.249609,0.253977
12,Idaho,0.278764,0.287386,0.284524,0.256279,0.180697,0.206078,0.231075,0.260614,0.280060,0.292378,0.347471,0.342280,0.328302,0.268278,0.252323,0.260572
13,Illinois,0.174327,0.180163,0.192298,0.226202,0.206118,0.206239,0.190735,0.203132,0.180296,0.194655,0.174593,0.164069,0.167273,0.162437,0.162622,NaN
14,Indiana,0.143097,0.152480,0.163937,NaN,0.173793,0.198113,0.198007,0.204782,0.225518,0.216934,0.217220,NaN,0.175749,NaN,NaN,0.191923
15,Iowa,0.119585,NaN,NaN,0.124469,0.096079,0.104486,0.101283,0.101494,0.100751,0.125107,0.125369,0.126261,0.121811,0.110756,0.105506,0.108322
16,Kansas,0.16097,0.157085,0.164939,0.182413,0.170665,0.194244,0.192035,0.197734,0.186534,0.180935,0.187061,0.166238,0.156019,0.134626,0.158497,0.165772
17,Kentucky,0.128517,0.126711,NaN,0.127540,0.134865,NaN,0.148690,0.156172,0.146001,0.135997,0.126765,0.131083,0.153953,0.152970,0.138561,0.134401
18,Louisiana,0.225718,0.233206,0.224275,0.227351,0.204089,0.189682,0.205668,0.209512,0.207090,0.203403,0.194133,0.184257,0.181509,0.191450,0.174548,0.176092
19,Maine,0.202788,0.217264,0.212638,0.249619,0.254992,0.253248,0.234260,0.235535,0.234522,NaN,0.207750,0.221695,0.207939,0.209594,NaN,0.214681
20,Maryland,NaN,0.379852,0.386830,0.380455,0.410281,0.454026,0.439001,NaN,NaN,0.486322,0.471892,0.454348,NaN,0.399485,NaN,NaN
21,Massachusetts,0.28939,0.292417,0.284938,0.291122,0.302696,NaN,0.295360,NaN,NaN,NaN,0.320762,0.287735,NaN,0.238446,NaN,NaN
22,Michigan,NaN,0.153532,0.147640,NaN,0.152237,0.168246,0.179768,0.183179,NaN,0.185548,0.184056,0.225346,0.212463,0.217944,0.193637,0.217470
23,Minnesota,0.180189,0.184377,0.181379,0.215808,0.207981,0.202598,0.200941,0.213468,NaN,0.197644,NaN,0.205493,NaN,NaN,0.196246,0.213760
24,Mississippi,0.17717,0.173372,0.177711,0.188679,0.179808,0.189772,0.202390,NaN,NaN,0.198997,0.190114,0.177320,0.164475,0.149470,0.159897,0.154828
25,Missouri,0.171177,0.178694,0.177561,0.167009,NaN,NaN,NaN,0.180031,NaN,0.180359,0.195520,0.191873,0.179556,0.154468,NaN,NaN
26,Montana,0.268477,0.298486,0.308694,0.341816,NaN,NaN,0.333148,0.327598,0.308156,0.302974,0.323381,0.324814,0.326490,0.268285,0.288666,0.315144
27,Nebraska,0.197828,0.188233,0.182027,0.184215,0.147594,0.158385,0.164709,0.175227,0.187922,0.200037,0.214636,0.199374,0.169863,0.171488,0.139142,0.127774
28,Nevada,0.185064,0.178441,0.176228,0.188415,0.173477,0.176025,0.201719,0.216429,0.238142,0.226232,0.227436,0.205950,0.221447,0.196706,NaN,0.164052
29,New Hampshire,0.182695,0.207016,0.217195,0.213522,0.213408,0.215894,0.203426,0.205495,0.206036,0.210540,0.222512,0.234450,0.228217,0.226339,0.220017,0.206763
30,New Jersey,0.302474,0.294538,0.258341,NaN,0.313813,0.341669,0.298901,0.307913,0.303083,0.314994,0.293635,0.276280,0.278489,0.315775,0.324394,0.324184
31,New Mexico,NaN,NaN,NaN,0.428195,0.672393,0.626007,0.677170,0.604455,0.672548,0.652573,0.612261,NaN,0.622690,NaN,0.569232,0.571654
32,New York,NaN,0.179159,0.177357,0.202319,0.201152,0.167601,0.161305,NaN,NaN,NaN,NaN,NaN,NaN,0.180376,0.173547,0.168875
33,North Carolina,NaN,NaN,0.255926,0.249186,NaN,0.253481,0.262783,0.280430,0.265278,0.299062,0.287811,0.278599,0.261329,0.260694,0.272428,0.264418
34,North Dakota,0.171636,0.144869,0.155242,0.151903,0.166681,0.159836,0.169669,0.151809,0.158760,0.228124,0.224623,0.199809,0.180876,0.209313,0.206398,0.204057
35,Ohio,NaN,0.190621,0.184635,0.202085,0.207625,0.202888,0.188746,0.208871,NaN,0.214869,NaN,0.210157,0.216632,NaN,0.199604,0.184610
36,Oklahoma,0.18918,0.231833,0.239021,0.254086,0.245276,0.188092,0.188156,0.205559,0.200232,0.252304,0.220674,0.198437,0.172184,NaN,0.172282,0.188789
37,Oregon,0.167209,0.172491,0.170755,NaN,0.171209,0.183976,0.186520,NaN,0.225007,0.241630,0.228007,0.200776,0.189025,0.168068,0.188443,0.181858
38,Pennsylvania,0.214763,0.192954,0.193022,0.203142,0.193181,0.200870,0.203493,0.219579,0.221472,NaN,0.254414,NaN,NaN,0.230206,0.222429,0.222310
39,Rhode Island,0.32892,0.351871,0.323045,0.213449,0.199642,0.215292,0.252856,0.232065,0.239478,0.209704,0.195133,0.198306,0.199453,0.197816,0.203820,0.190859
40,South Carolina,0.155881,0.182458,0.181945,0.180416,0.169334,0.165373,0.185812,0.179183,NaN,NaN,NaN,0.156676,0.126028,0.134356,0.141332,0.142076
41,South Dakota,0.153437,0.150939,0.147256,0.160008,NaN,0.189413,0.173076,0.167703,0.180813,NaN,0.193553,0.195480,0.186323,0.186817,0.164493,0.170491
42,Tennessee,0.169036,0.166600,NaN,0.186138,0.192755,0.182161,0.151992,0.153731,NaN,NaN,0.167034,0.148755,0.157414,0.139300,0.148504,0.151171
43,Texas,0.223924,0.231126,0.233540,0.241677,NaN,0.237504,0.286804,NaN,NaN,0.274590,NaN,0.266098,0.244890,0.240608,0.210750,0.207367
44,Utah,0.257786,0.249719,0.256543,0.263245,0.231309,0.238962,0.241193,0.255982,NaN,NaN,0.214052,0.206144,0.206877,0.201469,0.211247,NaN
45,Vermont,0.181881,0.195774,0.191500,0.186910,0.209205,0.209212,0.258398,0.236942,0.333528,0.312829,0.325187,0.265737,0.286608,0.301966,0.308086,0.268667
46,Virginia,NaN,NaN,0.248621,0.256621,0.252652,0.242170,0.256023,NaN,0.258628,0.255206,NaN,NaN,NaN,0.236402,0.249082,0.252293
47,Washington,0.296462,NaN,NaN,NaN,NaN,NaN,NaN,0.363877,0.379687,0.354910,0.355829,0.327428,0.337139,0.300609,0.289336,0.263259
48,West Virginia,0.246986,0.269904,0.282482,0.261765,0.245363,0.234068,0.227173,0.204891,0.182792,0.216737,0.205799,0.185101,0.181047,0.167756,0.203332,0.231116
49,Wisconsin,0.190891,0.201989,0.213388,0.223379,0.237284,0.214284,0.226418,0.203163,0.209059,0.163470,0.161193,0.157266,0.195194,0.193226,0.180520,0.150602
50,Wyoming,0.315706,0.364860,0.421320,0.381301,0.420983,0.404958,0.378828,0.359379,0.348534,0.399223,0.405149,0.392656,0.384033,0.369405,0.358236,0.375019

In [30]:
m = PhiSci4.mean(axis=1)
for i, col in enumerate(PhiSci4):
    PhiSci4.iloc[:, i] = PhiSci4.iloc[:, i].fillna(m)
PhiSci4 = PhiSci4.drop(['Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
                          'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45',
                          'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49'], axis = 1)

PhiSci4 = PhiSci4.rename(columns = {'Table S-36':'State',
                                       'Unnamed: 50':'Phsysial Scientists 2018 (Percent)'})

PhiSci4.head(10)

                  State  Phsysial Scientists 2018 (Percent)
0               Alabama                            0.143022
1                Alaska                            0.529738
2               Arizona                            0.164212
3              Arkansas                            0.126750
4            California                            0.231425
5              Colorado                            0.452119
6           Connecticut                            0.199976
7              Delaware                            0.497202
8  District of Columbia                            0.501144
9               Florida                            0.125920

In [31]:
PhiSciDF = [PhiSci2, PhiSci3, PhiSci4]

PhiSciFinal = reduce(lambda left, right: pd.merge(left, right, on = 'State', how = 'outer'), PhiSciDF)

PhiSciFinal

,State,Physical Scientists 2018,All Occupations 2018,Phsysial Scientists 2018 (Percent)
0,Alabama,2780.000000,1943760.0,0.143022
1,Alaska,1670.000000,315250.0,0.529738
2,Arizona,4174.000000,2789520.0,0.164212
3,Arkansas,1462.000000,1210120.0,0.126750
4,California,39360.000000,17007690.0,0.231425
5,Colorado,10467.272727,2620640.0,0.452119
6,Connecticut,3320.000000,1660200.0,0.199976
7,Delaware,2230.000000,448510.0,0.497202
8,District of Columbia,3570.000000,712370.0,0.501144
9,Florida,10840.000000,8608660.0,0.125920
10,Georgia,5110.000000,4394740.0,0.130659
11,Hawaii,1630.000000,641790.0,0.253977
12,Idaho,1840.000000,706140.0,0.260572
13,Illinois,10752.142857,5991270.0,0.186488
14,Indiana,5850.000000,3048100.0,0.191923
15,Iowa,1670.000000,1541700.0,0.108322
16,Kansas,2280.000000,1375380.0,0.165772
17,Kentucky,2540.000000,1889870.0,0.134401
18,Louisiana,3370.000000,1913770.0,0.176092
19,Maine,1300.000000,605550.0,0.214681
20,Maryland,10813.000000,2684010.0,0.426249
21,Massachusetts,9333.750000,3571360.0,0.289185
22,Michigan,9390.000000,4317830.0,0.217470
23,Minnesota,6130.000000,2867700.0,0.213760
24,Mississippi,1740.000000,1123830.0,0.154828
25,Missouri,4750.000000,2804780.0,0.178341
26,Montana,1460.000000,463280.0,0.315144
27,Nebraska,1250.000000,978290.0,0.127774
28,Nevada,2210.000000,1347130.0,0.164052
29,New Hampshire,1350.000000,652920.0,0.206763
30,New Jersey,13130.000000,4050170.0,0.324184
31,New Mexico,4640.000000,811680.0,0.571654
32,New York,15850.000000,9385620.0,0.168875
33,North Carolina,11590.000000,4383210.0,0.264418
34,North Dakota,850.000000,416550.0,0.204057
35,Ohio,10000.000000,5416810.0,0.184610
36,Oklahoma,3010.000000,1594370.0,0.188789
37,Oregon,3430.000000,1886090.0,0.181858
38,Pennsylvania,13000.000000,5847690.0,0.222310
39,Rhode Island,920.000000,482030.0,0.190859
40,South Carolina,2930.000000,2062280.0,0.142076
41,South Dakota,720.000000,422310.0,0.170491
42,Tennessee,4470.000000,2956920.0,0.151171
43,Texas,25120.000000,12113810.0,0.207367
44,Utah,2821.666667,1455910.0,0.231395
45,Vermont,820.000000,305210.0,0.268667
46,Virginia,9670.000000,3832840.0,0.252293
47,Washington,8580.000000,3259150.0,0.263259
48,West Virginia,1610.000000,696620.0,0.231116
49,Wisconsin,4290.000000,2848560.0,0.150602
50,Wyoming,1010.000000,269320.0,0.375019

In [32]:
COVIDCases = pd.read_csv('us-states.csv')
COVIDCases = COVIDCases.groupby(['state']).sum()
COVIDCases = COVIDCases.reset_index()
COVIDCases.drop([11, 36, 41, 49], inplace = True)
COVIDCases = COVIDCases.reset_index(drop = True)
COVIDCases.state

0                  Alabama
1                   Alaska
2                  Arizona
3                 Arkansas
4               California
5                 Colorado
6              Connecticut
7                 Delaware
8     District of Columbia
9                  Florida
10                 Georgia
11                  Hawaii
12                   Idaho
13                Illinois
14                 Indiana
15                    Iowa
16                  Kansas
17                Kentucky
18               Louisiana
19                   Maine
20                Maryland
21           Massachusetts
22                Michigan
23               Minnesota
24             Mississippi
25                Missouri
26                 Montana
27                Nebraska
28                  Nevada
29           New Hampshire
30              New Jersey
31              New Mexico
32                New York
33          North Carolina
34            North Dakota
35                    Ohio
36                Oklahoma
37                  Oregon
38            Pennsylvania
39            Rhode Island
40          South Carolina
41            South Dakota
42               Tennessee
43                   Texas
44                    Utah
45                 Vermont
46                Virginia
47              Washington
48           West Virginia
49               Wisconsin
50                 Wyoming
Name: state, dtype: object

In [33]:
COVIDCases = COVIDCases.rename(columns = {'state':'State'})
COVIDCases.head()

        State  fips    cases  deaths
0     Alabama    73   387786   14345
1      Alaska   148    18316     367
2     Arizona   480   426614   18857
3    Arkansas   375   161569    3301
4  California   726  2664110  102387

In [34]:
COVIDPhiSci = pd.merge(COVIDCases, PhiSciFinal, how = 'left', on = 'State')
COVIDPhiSci

,State,fips,cases,deaths,Physical Scientists 2018,All Occupations 2018,Phsysial Scientists 2018 (Percent)
0,Alabama,73,387786,14345,2780.000000,1943760.0,0.143022
1,Alaska,148,18316,367,1670.000000,315250.0,0.529738
2,Arizona,480,426614,18857,4174.000000,2789520.0,0.164212
3,Arkansas,375,161569,3301,1462.000000,1210120.0,0.126750
4,California,726,2664110,102387,39360.000000,17007690.0,0.231425
5,Colorado,648,766512,37828,10467.272727,2620640.0,0.452119
6,Connecticut,702,1314995,104185,3320.000000,1660200.0,0.199976
7,Delaware,750,234327,7813,2230.000000,448510.0,0.497202
8,District of Columbia,869,229466,10822,3570.000000,712370.0,0.501144
9,Florida,1020,1726811,63147,10840.000000,8608660.0,0.125920
10,Georgia,1092,1282091,54209,5110.000000,4394740.0,0.130659
11,Hawaii,1200,31433,681,1630.000000,641790.0,0.253977
12,Idaho,1168,103987,2828,1840.000000,706140.0,0.260572
13,Illinois,2074,2843621,122000,10752.142857,5991270.0,0.186488
14,Indiana,1440,920434,53042,5850.000000,3048100.0,0.191923
15,Iowa,1482,396980,9203,1670.000000,1541700.0,0.108322
16,Kansas,1580,231885,6527,2280.000000,1375380.0,0.165772
17,Kentucky,1680,246480,11851,2540.000000,1889870.0,0.134401
18,Louisiana,1694,1443404,90609,3370.000000,1913770.0,0.176092
19,Maine,1702,61284,2451,1300.000000,605550.0,0.214681
20,Maryland,1944,1173802,56126,10813.000000,2684010.0,0.426249
21,Massachusetts,2850,2929874,167711,9333.750000,3571360.0,0.289185
22,Michigan,1976,2023047,171867,9390.000000,4317830.0,0.217470
23,Minnesota,2160,377850,18934,6130.000000,2867700.0,0.213760
24,Mississippi,2100,358459,15047,1740.000000,1123830.0,0.154828
25,Missouri,2291,395952,17924,4750.000000,2804780.0,0.178341
26,Montana,2190,23875,676,1460.000000,463280.0,0.315144
27,Nebraska,3038,259429,3535,1250.000000,978290.0,0.127774
28,Nevada,2592,259808,11975,2210.000000,1347130.0,0.164052
29,New Hampshire,2772,117245,4507,1350.000000,652920.0,0.206763
30,New Jersey,2788,5645458,332869,13130.000000,4050170.0,0.324184
31,New Mexico,2625,177827,6867,4640.000000,811680.0,0.571654
32,New York,3060,15041806,1081194,15850.000000,9385620.0,0.168875
33,North Carolina,3071,568719,19258,11590.000000,4383210.0,0.264418
34,North Dakota,2850,55932,1219,850.000000,416550.0,0.204057
35,Ohio,3003,908834,47879,10000.000000,5416810.0,0.184610
36,Oklahoma,3200,187462,10394,3010.000000,1594370.0,0.188789
37,Oregon,3567,134979,5067,3430.000000,1886090.0,0.181858
38,Pennsylvania,3360,2320771,127278,13000.000000,5847690.0,0.222310
39,Rhode Island,3740,401931,14251,920.000000,482030.0,0.190859
40,South Carolina,3600,313173,11859,2930.000000,2062280.0,0.142076
41,South Dakota,3496,122292,1121,720.000000,422310.0,0.170491
42,Tennessee,3807,583792,10198,4470.000000,2956920.0,0.151171
43,Texas,4944,1553075,41267,25120.000000,12113810.0,0.207367
44,Utah,4410,245859,2472,2821.666667,1455910.0,0.231395
45,Vermont,3950,45230,2320,820.000000,305210.0,0.268667
46,Virginia,4029,866807,28754,9670.000000,3832840.0,0.252293
47,Washington,6625,807848,42371,8580.000000,3259150.0,0.263259
48,West Virginia,3726,56158,1950,1610.000000,696620.0,0.231116
49,Wisconsin,6050,393823,15587,4290.000000,2848560.0,0.150602
50,Wyoming,4200,28407,281,1010.000000,269320.0,0.375019

In [35]:
COVIDPhiSci = COVIDPhiSci.drop(['fips'], axis = 1)
COVIDPhiSci

,State,cases,deaths,Physical Scientists 2018,All Occupations 2018,Phsysial Scientists 2018 (Percent)
0,Alabama,387786,14345,2780.000000,1943760.0,0.143022
1,Alaska,18316,367,1670.000000,315250.0,0.529738
2,Arizona,426614,18857,4174.000000,2789520.0,0.164212
3,Arkansas,161569,3301,1462.000000,1210120.0,0.126750
4,California,2664110,102387,39360.000000,17007690.0,0.231425
5,Colorado,766512,37828,10467.272727,2620640.0,0.452119
6,Connecticut,1314995,104185,3320.000000,1660200.0,0.199976
7,Delaware,234327,7813,2230.000000,448510.0,0.497202
8,District of Columbia,229466,10822,3570.000000,712370.0,0.501144
9,Florida,1726811,63147,10840.000000,8608660.0,0.125920
10,Georgia,1282091,54209,5110.000000,4394740.0,0.130659
11,Hawaii,31433,681,1630.000000,641790.0,0.253977
12,Idaho,103987,2828,1840.000000,706140.0,0.260572
13,Illinois,2843621,122000,10752.142857,5991270.0,0.186488
14,Indiana,920434,53042,5850.000000,3048100.0,0.191923
15,Iowa,396980,9203,1670.000000,1541700.0,0.108322
16,Kansas,231885,6527,2280.000000,1375380.0,0.165772
17,Kentucky,246480,11851,2540.000000,1889870.0,0.134401
18,Louisiana,1443404,90609,3370.000000,1913770.0,0.176092
19,Maine,61284,2451,1300.000000,605550.0,0.214681
20,Maryland,1173802,56126,10813.000000,2684010.0,0.426249
21,Massachusetts,2929874,167711,9333.750000,3571360.0,0.289185
22,Michigan,2023047,171867,9390.000000,4317830.0,0.217470
23,Minnesota,377850,18934,6130.000000,2867700.0,0.213760
24,Mississippi,358459,15047,1740.000000,1123830.0,0.154828
25,Missouri,395952,17924,4750.000000,2804780.0,0.178341
26,Montana,23875,676,1460.000000,463280.0,0.315144
27,Nebraska,259429,3535,1250.000000,978290.0,0.127774
28,Nevada,259808,11975,2210.000000,1347130.0,0.164052
29,New Hampshire,117245,4507,1350.000000,652920.0,0.206763
30,New Jersey,5645458,332869,13130.000000,4050170.0,0.324184
31,New Mexico,177827,6867,4640.000000,811680.0,0.571654
32,New York,15041806,1081194,15850.000000,9385620.0,0.168875
33,North Carolina,568719,19258,11590.000000,4383210.0,0.264418
34,North Dakota,55932,1219,850.000000,416550.0,0.204057
35,Ohio,908834,47879,10000.000000,5416810.0,0.184610
36,Oklahoma,187462,10394,3010.000000,1594370.0,0.188789
37,Oregon,134979,5067,3430.000000,1886090.0,0.181858
38,Pennsylvania,2320771,127278,13000.000000,5847690.0,0.222310
39,Rhode Island,401931,14251,920.000000,482030.0,0.190859
40,South Carolina,313173,11859,2930.000000,2062280.0,0.142076
41,South Dakota,122292,1121,720.000000,422310.0,0.170491
42,Tennessee,583792,10198,4470.000000,2956920.0,0.151171
43,Texas,1553075,41267,25120.000000,12113810.0,0.207367
44,Utah,245859,2472,2821.666667,1455910.0,0.231395
45,Vermont,45230,2320,820.000000,305210.0,0.268667
46,Virginia,866807,28754,9670.000000,3832840.0,0.252293
47,Washington,807848,42371,8580.000000,3259150.0,0.263259
48,West Virginia,56158,1950,1610.000000,696620.0,0.231116
49,Wisconsin,393823,15587,4290.000000,2848560.0,0.150602
50,Wyoming,28407,281,1010.000000,269320.0,0.375019