In [1]:
import pandas as pd
import numpy as np
from functools import reduce

In [2]:
SocSci = pd.read_excel('social-scientists-to-all-occupations.xlsx')
SocSci

,Table S-37,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
0,Social Scientists as a Percentage of All Occup...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Social scientists,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,2003,2004.0,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,...,2009.000000,2010.000000,2011.000000,2012.000000,2013.00000,2014.00000,2015.000000,2016.000000,2017.000000,2018.000000
3,United States,461060,497280.0,517950.0,536880.0,545360.0,561160.0,568730.0,349820.0,433320.0,...,0.435316,0.275238,0.337796,0.279458,0.28031,0.27445,0.269332,0.268568,0.264884,0.267008
4,Alabama,3470,4090.0,4270.0,4090.0,3550.0,3050.0,NaN,NaN,2810.0,...,NaN,NaN,0.155298,0.141964,0.14533,NaN,0.134338,0.119708,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,NOTES: Occupational Employment Statistics (OES...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,"SOURCE: Bureau of Labor Statistics, special ta...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,Recommended Citation: National Science Board. ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,"Last updated: September 24, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Science and Engineering Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
SocSci2 = SocSci.drop(['Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
                          'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
                          'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32',
                          'Unnamed: 34', 'Unnamed: 33', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
                          'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45',
                          'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50'], axis = 1)

SocSci2.head()

,Table S-37,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Social Scientists as a Percentage of All Occup...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Social scientists,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,2003,2004.0,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0
3,United States,461060,497280.0,517950.0,536880.0,545360.0,561160.0,568730.0,349820.0,433320.0,364100.0,371660.0,370860.0,371400.0,377070.0,377590.0,386450.0
4,Alabama,3470,4090.0,4270.0,4090.0,3550.0,3050.0,NaN,NaN,2810.0,2590.0,2680.0,NaN,2530.0,2290.0,NaN,NaN

In [4]:
SocSci2.drop(range(0,4), inplace = True)
SocSci2.drop(range(55,64), inplace = True)
SocSci2 = SocSci2.reset_index(drop = True)
SocSci2

,Table S-37,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Alabama,3470,4090.0,4270.0,4090.0,3550.0,3050.0,NaN,NaN,2810.0,2590.0,2680.0,NaN,2530.0,2290.0,NaN,NaN
1,Alaska,1130,1150.0,1260.0,1070.0,970.0,1020.0,1200.0,1040.0,1250.0,1230.0,1180.0,1080.0,1060.0,1170.0,1200.0,1090.0
2,Arizona,7690,8130.0,8380.0,8570.0,9050.0,8880.0,9760.0,7860.0,10560.0,7300.0,6780.0,6400.0,7720.0,7350.0,7590.0,7870.0
3,Arkansas,2250,2650.0,2500.0,2420.0,3050.0,3240.0,3540.0,2070.0,2370.0,1990.0,2070.0,1980.0,NaN,1780.0,1890.0,NaN
4,California,56540,60540.0,62940.0,63470.0,65510.0,71800.0,77120.0,45810.0,59080.0,50370.0,50390.0,51780.0,50960.0,50660.0,48770.0,50350.0
5,Colorado,8760,8510.0,8600.0,9660.0,9770.0,9570.0,8960.0,6610.0,NaN,6820.0,6910.0,7210.0,7220.0,7630.0,7560.0,NaN
6,Connecticut,8710,8800.0,8630.0,7770.0,7580.0,7910.0,8140.0,5210.0,6760.0,5450.0,5140.0,4770.0,4940.0,4680.0,4380.0,4830.0
7,Delaware,1910,2180.0,1760.0,2980.0,3450.0,3200.0,2960.0,1000.0,1890.0,960.0,1000.0,980.0,1020.0,1080.0,1150.0,1230.0
8,District of Columbia,13370,15770.0,17890.0,17310.0,17020.0,17500.0,16830.0,14600.0,16140.0,15730.0,16660.0,18660.0,18900.0,21630.0,20580.0,18400.0
9,Florida,19850,23130.0,25430.0,24570.0,21580.0,20180.0,20390.0,NaN,15780.0,14300.0,14500.0,14320.0,12720.0,12740.0,14900.0,15880.0
10,Georgia,10150,10330.0,11430.0,11540.0,12390.0,13620.0,14480.0,8180.0,9810.0,7220.0,7100.0,7590.0,NaN,7420.0,8360.0,9520.0
11,Hawaii,1890,2370.0,2300.0,2670.0,2890.0,2830.0,2910.0,2800.0,2660.0,2550.0,2490.0,2750.0,2730.0,2840.0,2610.0,2480.0
12,Idaho,1590,1560.0,1650.0,NaN,2510.0,2110.0,2110.0,1480.0,1770.0,1870.0,1890.0,1790.0,1520.0,1540.0,1340.0,1340.0
13,Illinois,23590,25210.0,24970.0,25970.0,25470.0,25100.0,24140.0,11180.0,16440.0,11700.0,11820.0,10980.0,10950.0,11990.0,12660.0,NaN
14,Indiana,5870,6340.0,6370.0,6210.0,6330.0,7350.0,8200.0,5880.0,7440.0,6310.0,6390.0,NaN,5760.0,5940.0,5610.0,NaN
15,Iowa,3740,4090.0,4100.0,4700.0,5200.0,5280.0,5520.0,2870.0,4010.0,2770.0,2630.0,2420.0,2390.0,2550.0,2680.0,2740.0
16,Kansas,4880,4650.0,4750.0,4790.0,5140.0,6020.0,6270.0,3760.0,4510.0,3560.0,3480.0,2690.0,2720.0,2700.0,2840.0,2790.0
17,Kentucky,3910,4160.0,4370.0,4480.0,4810.0,4990.0,4920.0,3970.0,4300.0,3880.0,3900.0,3720.0,3750.0,3870.0,3630.0,3460.0
18,Louisiana,3640,3600.0,3350.0,3340.0,NaN,3090.0,3250.0,2520.0,NaN,NaN,2000.0,2240.0,2280.0,2310.0,2330.0,2680.0
19,Maine,1340,1470.0,1630.0,1690.0,1740.0,1880.0,1810.0,1560.0,1660.0,1610.0,1600.0,1410.0,1420.0,1380.0,1470.0,1430.0
20,Maryland,13080,13710.0,14380.0,13870.0,15000.0,14990.0,14970.0,NaN,NaN,10530.0,9980.0,9490.0,NaN,10350.0,NaN,NaN
21,Massachusetts,19160,19610.0,19830.0,20870.0,21300.0,22900.0,24290.0,NaN,NaN,NaN,15180.0,15050.0,NaN,15700.0,15510.0,NaN
22,Michigan,14330,13090.0,13440.0,14590.0,15360.0,17260.0,16440.0,9920.0,11280.0,9400.0,9620.0,8150.0,8400.0,8420.0,7710.0,8330.0
23,Minnesota,11940,13670.0,14090.0,14400.0,14540.0,14000.0,13790.0,6160.0,9170.0,6000.0,NaN,6530.0,NaN,7310.0,8430.0,9240.0
24,Mississippi,1950,1890.0,1890.0,2090.0,2230.0,2600.0,2810.0,2360.0,2260.0,NaN,1890.0,NaN,1680.0,1450.0,1530.0,1350.0
25,Missouri,6490,7440.0,8840.0,9430.0,9550.0,8410.0,7950.0,4960.0,5900.0,5200.0,4470.0,4670.0,4730.0,4870.0,4690.0,NaN
26,Montana,1220,1540.0,1750.0,1740.0,NaN,1520.0,1610.0,1170.0,1220.0,1240.0,1240.0,1210.0,1270.0,1570.0,1510.0,1510.0
27,Nebraska,3590,3760.0,3890.0,3900.0,3560.0,3500.0,3910.0,1760.0,2780.0,1840.0,2100.0,2200.0,2250.0,2140.0,2290.0,2350.0
28,Nevada,2650,3350.0,2980.0,3500.0,3130.0,2870.0,2790.0,1900.0,2490.0,1760.0,1770.0,1730.0,1800.0,1880.0,1870.0,1950.0
29,New Hampshire,1930,1880.0,2040.0,1780.0,1820.0,1960.0,2030.0,1610.0,1530.0,1220.0,1280.0,1350.0,1420.0,1450.0,1570.0,1570.0
30,New Jersey,12220,16210.0,17730.0,NaN,17390.0,15270.0,14510.0,7640.0,9380.0,7850.0,8560.0,9120.0,9360.0,9800.0,9290.0,8840.0
31,New Mexico,2810,3540.0,3580.0,3340.0,3510.0,4240.0,3920.0,3830.0,2660.0,2520.0,2450.0,2570.0,2770.0,2630.0,2940.0,2890.0
32,New York,37710,41600.0,44120.0,46130.0,46890.0,49580.0,50160.0,28950.0,37310.0,32880.0,35100.0,NaN,35190.0,36420.0,35850.0,37090.0
33,North Carolina,12370,13050.0,13560.0,14300.0,14040.0,15610.0,16660.0,10630.0,12930.0,10610.0,10910.0,10860.0,11390.0,11710.0,11950.0,11800.0
34,North Dakota,750,740.0,780.0,920.0,740.0,730.0,770.0,520.0,680.0,670.0,720.0,760.0,760.0,810.0,840.0,780.0
35,Ohio,16360,16890.0,NaN,16410.0,17190.0,18310.0,18140.0,10540.0,12940.0,10800.0,10680.0,10250.0,NaN,9990.0,10830.0,11470.0
36,Oklahoma,5220,4600.0,4660.0,5220.0,5090.0,5180.0,4670.0,3050.0,5270.0,4840.0,5150.0,2730.0,2740.0,2690.0,3160.0,3160.0
37,Oregon,5490,5560.0,5320.0,6040.0,6670.0,6460.0,6560.0,5030.0,6090.0,5430.0,5500.0,4980.0,4920.0,4620.0,4900.0,5030.0
38,Pennsylvania,18810,21410.0,23910.0,NaN,26550.0,28000.0,NaN,16960.0,22440.0,19060.0,19800.0,19950.0,18740.0,17350.0,15620.0,15000.0
39,Rhode Island,2020,1830.0,1650.0,1730.0,1760.0,1730.0,1660.0,1320.0,1660.0,1720.0,1650.0,1540.0,1520.0,1530.0,1630.0,1730.0
40,South Carolina,4550,3890.0,3720.0,4000.0,4320.0,4830.0,5030.0,3570.0,4110.0,3630.0,3600.0,3310.0,3120.0,3340.0,3410.0,3230.0
41,South Dakota,830,960.0,1150.0,1110.0,1100.0,1060.0,1100.0,1020.0,1010.0,NaN,950.0,1010.0,1120.0,1090.0,990.0,1010.0
42,Tennessee,5360,5480.0,5150.0,6190.0,6850.0,7240.0,6540.0,4240.0,5210.0,4680.0,4870.0,5070.0,5290.0,4800.0,4850.0,5410.0
43,Texas,25480,28010.0,29250.0,32520.0,34970.0,35650.0,35610.0,20610.0,25830.0,20180.0,21410.0,21790.0,22340.0,22510.0,22680.0,23740.0
44,Utah,4280,4740.0,4610.0,5190.0,4620.0,4560.0,4210.0,3100.0,3110.0,2980.0,3170.0,3620.0,3790.0,3810.0,3940.0,3910.0
45,Vermont,1640,1710.0,1900.0,2060.0,2140.0,2020.0,2010.0,1200.0,1530.0,1310.0,1320.0,1480.0,1590.0,1600.0,1400.0,1310.0
46,Virginia,16820,18940.0,20480.0,22450.0,21830.0,21370.0,20620.0,12100.0,14890.0,12650.0,13450.0,13980.0,14770.0,15700.0,16190.0,NaN
47,Washington,14420,16410.0,16550.0,17650.0,17620.0,18030.0,18420.0,9240.0,11350.0,8770.0,NaN,NaN,9130.0,9240.0,9560.0,9360.0
48,West Virginia,2260,2040.0,2050.0,2110.0,1970.0,2240.0,2170.0,1920.0,2160.0,2450.0,2680.0,2630.0,2740.0,2090.0,1940.0,1920.0
49,Wisconsin,10320,10180.0,10650.0,10060.0,9840.0,9430.0,9570.0,5830.0,7000.0,5790.0,6070.0,6670.0,5870.0,5890.0,5740.0,7150.0
50,Wyoming,700,830.0,830.0,900.0,940.0,1020.0,NaN,770.0,930.0,740.0,NaN,790.0,810.0,740.0,740.0,760.0

In [5]:
m = SocSci2.mean(axis=1)
for i, col in enumerate(SocSci2):
    SocSci2.iloc[:, i] = SocSci2.iloc[:, i].fillna(m)
SocSci2 = SocSci2.drop(['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
                          'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
                          'Unnamed: 14', 'Unnamed: 15'], axis = 1)

SocSci2 = SocSci2.rename(columns = {'Table S-37':'State',
                                       'Unnamed: 16':'Social Scientists 2018'})

SocSci2.head(10)

                  State  Social Scientists 2018
0               Alabama             3195.000000
1                Alaska             1090.000000
2               Arizona             7870.000000
3              Arkansas             2426.923077
4            California            50350.000000
5              Colorado             8079.230769
6           Connecticut             4830.000000
7              Delaware             1230.000000
8  District of Columbia            18400.000000
9               Florida            15880.000000

In [6]:
SocSci3 = SocSci.drop(['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
                          'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
                          'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
                          'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45',
                          'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50'], axis = 1)

SocSci3.head()

,Table S-37,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,Social Scientists as a Percentage of All Occup...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,All occupations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,2003,2004.0,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0
3,United States,127420170,129146700.0,130307840.0,132604980.0,134354250.0,135185230.0,130647610.0,127097160.0,128278550.0,130287700.0,132588810.0,135128260.0,137896660.0,140400040.0,142549250.0,144733270.0
4,Alabama,1817240,1851040.0,1872600.0,1912220.0,1931970.0,1945300.0,1863620.0,1807480.0,1809420.0,1824400.0,1844080.0,1857530.0,1883310.0,1912990.0,1922570.0,1943760.0

In [7]:
SocSci3.drop(range(0,4), inplace = True)
SocSci3.drop(range(55,64), inplace = True)
SocSci3 = SocSci3.reset_index(drop = True)
SocSci3

,Table S-37,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,Alabama,1817240,1851040.0,1872600.0,1912220.0,1931970.0,1945300.0,1863620.0,1807480.0,1809420.0,1824400.0,1844080.0,1857530.0,1883310.0,1912990.0,1922570.0,1943760.0
1,Alaska,290740,295810.0,300150.0,303890.0,301920.0,307790.0,308140.0,308050.0,313170.0,318700.0,322660.0,324970.0,327250.0,323500.0,318170.0,315250.0
2,Arizona,2275410,2370810.0,2437100.0,2574150.0,2648000.0,2637830.0,2479120.0,2367120.0,2380200.0,2414340.0,2475660.0,2526990.0,2587070.0,2652990.0,2704050.0,2789520.0
3,Arkansas,1118690,1133800.0,1142370.0,1166840.0,1172760.0,1176050.0,1147660.0,1135560.0,1139670.0,1155020.0,1152600.0,1158790.0,1176130.0,1191320.0,1200130.0,1210120.0
4,California,14460860,14598250.0,14723900.0,15065750.0,15202530.0,15212610.0,14532640.0,14001730.0,14038950.0,14303630.0,14714530.0,15119730.0,15496600.0,15966580.0,16695010.0,17007690.0
5,Colorado,2097650,2130430.0,2151520.0,2207120.0,2258240.0,2302340.0,2234250.0,2157690.0,2179060.0,2226160.0,2295000.0,2367780.0,2451490.0,2507680.0,2555300.0,2620640.0
6,Connecticut,1631610,1640840.0,1648070.0,1658980.0,1682220.0,1697810.0,1648950.0,1598640.0,1608820.0,1620620.0,1635590.0,1646510.0,1659430.0,1666280.0,1654420.0,1660200.0
7,Delaware,403650,413940.0,417550.0,424270.0,425960.0,425210.0,412570.0,397730.0,403430.0,405750.0,412140.0,424330.0,433840.0,440760.0,442690.0,448510.0
8,District of Columbia,595220,609770.0,611190.0,609400.0,620970.0,635500.0,637180.0,639390.0,644730.0,653760.0,665850.0,674650.0,676060.0,702380.0,708220.0,712370.0
9,Florida,7217400,7479050.0,7614840.0,7869210.0,7963010.0,7771740.0,7355940.0,7103950.0,7151700.0,7273850.0,7453230.0,7665280.0,7925300.0,8222030.0,8419030.0,8608660.0
10,Georgia,3770430,3848740.0,3904020.0,4001580.0,4058370.0,4068270.0,3889160.0,3744740.0,3779250.0,3815530.0,3879660.0,3983250.0,4107960.0,4214410.0,4303530.0,4394740.0
11,Hawaii,557400,573890.0,583630.0,599130.0,610310.0,612420.0,587810.0,571630.0,577220.0,588210.0,602200.0,612580.0,619960.0,632120.0,632990.0,641790.0
12,Idaho,563200,584580.0,597490.0,624320.0,641960.0,650240.0,614520.0,594750.0,592730.0,598540.0,613000.0,628140.0,642700.0,663490.0,685630.0,706140.0
13,Illinois,5719150,5739250.0,5767100.0,5826660.0,5894670.0,5910630.0,5704240.0,5528420.0,5574180.0,5640740.0,5704700.0,5765880.0,5852710.0,5903820.0,5927860.0,5991270.0
14,Indiana,2851210,2879070.0,2891360.0,2913200.0,2928780.0,2927620.0,2787780.0,2724850.0,2758100.0,2811920.0,2854250.0,2905170.0,2947380.0,2991260.0,3018490.0,3048100.0
15,Iowa,1413220,1433570.0,1446550.0,1470240.0,1488360.0,1502600.0,1471130.0,1438510.0,1449110.0,1470740.0,1491600.0,1512740.0,1526950.0,1534910.0,1535460.0,1541700.0
16,Kansas,1292170,1311390.0,1315640.0,1321180.0,1347670.0,1374560.0,1348710.0,1304780.0,1308070.0,1320920.0,1336460.0,1359500.0,1371630.0,1374180.0,1369110.0,1375380.0
17,Kentucky,1719620,1736230.0,1754590.0,1779830.0,1801800.0,1817860.0,1748610.0,1716060.0,1732870.0,1764750.0,1782820.0,1808010.0,1838220.0,1869650.0,1876430.0,1889870.0
18,Louisiana,1851870,1865300.0,1877160.0,1776990.0,1847230.0,1887370.0,1871950.0,1832830.0,1839780.0,1868210.0,1885310.0,1915800.0,1939300.0,1922170.0,1902060.0,1913770.0
19,Maine,591750,598350.0,597260.0,596910.0,600020.0,604150.0,589090.0,577410.0,575640.0,581110.0,582430.0,586390.0,591520.0,596390.0,599180.0,605550.0
20,Maryland,2448580,2477280.0,2497220.0,2531180.0,2551910.0,2561530.0,2503410.0,2462470.0,2480670.0,2510680.0,2534480.0,2557510.0,2596630.0,2640900.0,2664330.0,2684010.0
21,Massachusetts,3130720,3129090.0,3144540.0,3170490.0,3207840.0,3234860.0,3169010.0,3119100.0,3157020.0,3202080.0,3257870.0,3322500.0,3396840.0,3459910.0,3528070.0,3571360.0
22,Michigan,4310420,4324840.0,4334870.0,4294260.0,4210550.0,4142750.0,3893900.0,3755890.0,3829000.0,3918120.0,3998790.0,4073730.0,4146600.0,4212090.0,4276040.0,4317830.0
23,Minnesota,2591720,2625060.0,2635370.0,2682940.0,2687740.0,2704860.0,2627640.0,2562450.0,2595450.0,2641110.0,2688580.0,2730020.0,2772240.0,2810400.0,2838270.0,2867700.0
24,Mississippi,1089350,1101680.0,1108540.0,1113000.0,1128980.0,1138210.0,1096890.0,1070820.0,1073100.0,1080420.0,1083560.0,1094070.0,1106550.0,1117280.0,1119470.0,1123830.0
25,Missouri,2623020,2646990.0,2663880.0,2700450.0,2732920.0,2740170.0,2668450.0,2588450.0,2591020.0,2605910.0,2639120.0,2673640.0,2712240.0,2757850.0,2788680.0,2804780.0
26,Montana,394820,408730.0,414650.0,427130.0,435480.0,444090.0,432240.0,424300.0,425110.0,432380.0,439110.0,443330.0,447180.0,454740.0,460740.0,463280.0
27,Nebraska,879550,887200.0,895470.0,901120.0,914670.0,928120.0,916770.0,901690.0,904630.0,914830.0,927150.0,942950.0,953710.0,968000.0,970230.0,978290.0
28,Nevada,1086110,1154440.0,1191640.0,1257860.0,1285470.0,1278230.0,1179860.0,1113530.0,1112780.0,1127160.0,1151970.0,1189610.0,1232800.0,1270930.0,1310220.0,1347130.0
29,New Hampshire,607570,618310.0,621560.0,627570.0,632590.0,634570.0,619390.0,603420.0,606690.0,612710.0,620190.0,627000.0,635360.0,645050.0,649950.0,652920.0
30,New Jersey,3878020,3901020.0,3917310.0,3957500.0,3980080.0,3986310.0,3850770.0,3770550.0,3771250.0,3793720.0,3821070.0,3869260.0,3906800.0,3955350.0,4007470.0,4050170.0
31,New Mexico,747050,754990.0,763430.0,789360.0,798640.0,819480.0,800390.0,777560.0,777640.0,773860.0,783980.0,788000.0,798150.0,805440.0,801080.0,811680.0
32,New York,8236200,8299910.0,8333460.0,8387750.0,8515960.0,8633580.0,8487020.0,8344020.0,8427560.0,8542280.0,8635400.0,8810950.0,8984890.0,9097650.0,9207870.0,9385620.0
33,North Carolina,3702170,3770700.0,3809690.0,3892670.0,4013460.0,4063420.0,3896750.0,3772780.0,3814860.0,3878800.0,3947030.0,4030880.0,4125070.0,4231020.0,4298390.0,4383210.0
34,North Dakota,314620,324430.0,328520.0,335740.0,341970.0,350360.0,353630.0,355710.0,371630.0,403290.0,422930.0,440420.0,447820.0,425200.0,416670.0,416550.0
35,Ohio,5308270,5324700.0,5340280.0,5354170.0,5341360.0,5323130.0,5091490.0,4921690.0,4977910.0,5054250.0,5125850.0,5200880.0,5280850.0,5337890.0,5370640.0,5416810.0
36,Oklahoma,1416640,1436380.0,1455940.0,1503430.0,1528890.0,1557750.0,1525330.0,1483760.0,1498260.0,1529900.0,1558860.0,1577330.0,1597130.0,1586890.0,1573000.0,1594370.0
37,Oregon,1537000,1576890.0,1598780.0,1648680.0,1682150.0,1706740.0,1624490.0,1569700.0,1586620.0,1609900.0,1640300.0,1683470.0,1735220.0,1790940.0,1830790.0,1886090.0
38,Pennsylvania,5494430,5535000.0,5569310.0,5631520.0,5663070.0,5705170.0,5572660.0,5483220.0,5549240.0,5596480.0,5616820.0,5653840.0,5709480.0,5747020.0,5781610.0,5847690.0
39,Rhode Island,477320,480290.0,479810.0,482550.0,485870.0,478420.0,458760.0,448150.0,450980.0,453020.0,456100.0,463930.0,471290.0,475190.0,475910.0,482030.0
40,South Carolina,1764170,1792190.0,1802740.0,1840190.0,1877950.0,1892690.0,1802900.0,1746820.0,1772880.0,1796550.0,1826120.0,1876480.0,1928140.0,1979820.0,2009460.0,2062280.0
41,South Dakota,364970,371010.0,373500.0,381230.0,389400.0,395960.0,392890.0,387590.0,392670.0,398680.0,402990.0,409250.0,413260.0,417520.0,419470.0,422310.0
42,Tennessee,2614830,2665060.0,2686580.0,2718410.0,2739230.0,2755800.0,2625140.0,2569420.0,2602320.0,2657280.0,2700050.0,2749480.0,2814230.0,2893040.0,2915750.0,2956920.0
43,Texas,9248660,9306600.0,9424510.0,9760960.0,10061750.0,10391420.0,10289240.0,10089870.0,10304370.0,10579400.0,10913950.0,11228940.0,11572540.0,11745250.0,11890880.0,12113810.0
44,Utah,1043500,1077210.0,1099230.0,1151020.0,1206180.0,1230320.0,1185770.0,1148520.0,1165980.0,1200850.0,1242690.0,1280660.0,1324460.0,1374900.0,1410670.0,1455910.0
45,Vermont,291400,296260.0,297650.0,299610.0,301140.0,301130.0,294120.0,286990.0,290830.0,294090.0,298290.0,301050.0,303550.0,304670.0,305110.0,305210.0
46,Virginia,3412070,3494250.0,3535500.0,3608430.0,3645330.0,3670980.0,3589520.0,3527350.0,3553360.0,3597100.0,3631440.0,3648490.0,3682450.0,3760550.0,3789910.0,3832840.0
47,Washington,2560190,2614640.0,2653320.0,2736910.0,2811700.0,2868910.0,2789670.0,2693220.0,2720660.0,2764080.0,2827200.0,2898350.0,2983930.0,3067110.0,3186610.0,3259150.0
48,West Virginia,680200,692840.0,697390.0,710560.0,713230.0,717740.0,704310.0,688170.0,700250.0,710540.0,709430.0,707720.0,707000.0,697440.0,688530.0,696620.0
49,Wisconsin,2687400,2717970.0,2727430.0,2744210.0,2768830.0,2776690.0,2689710.0,2608740.0,2645180.0,2673280.0,2704840.0,2727860.0,2771600.0,2805010.0,2825170.0,2848560.0
50,Wyoming,240730,246670.0,251590.0,262260.0,273170.0,283980.0,282450.0,269910.0,272570.0,278040.0,278910.0,282690.0,283830.0,276120.0,267980.0,269320.0

In [8]:
m = SocSci3.mean(axis=1)
for i, col in enumerate(SocSci3):
    SocSci3.iloc[:, i] = SocSci3.iloc[:, i].fillna(m)
SocSci3 = SocSci3.drop(['Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
                          'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
                          'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32',], axis = 1)

SocSci3 = SocSci3.rename(columns = {'Table S-37':'State',
                                       'Unnamed: 33':'All Occupations 2018'})

SocSci3.head(10)

                  State  All Occupations 2018
0               Alabama             1943760.0
1                Alaska              315250.0
2               Arizona             2789520.0
3              Arkansas             1210120.0
4            California            17007690.0
5              Colorado             2620640.0
6           Connecticut             1660200.0
7              Delaware              448510.0
8  District of Columbia              712370.0
9               Florida             8608660.0

In [9]:
SocSci4 = SocSci.drop(['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
                          'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
                          'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
                          'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
                          'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
                          'Unnamed: 34',], axis = 1)

SocSci4.head()

,Table S-37,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
0,Social Scientists as a Percentage of All Occup...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Social scientists in all occupations (Percent),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,2003,2004.000000,2005.000000,2006.000000,2007.000000,2008.000000,2009.000000,2010.000000,2011.000000,2012.000000,2013.00000,2014.00000,2015.000000,2016.000000,2017.000000,2018.000000
3,United States,0.361842,0.385050,0.397482,0.404872,0.405912,0.415105,0.435316,0.275238,0.337796,0.279458,0.28031,0.27445,0.269332,0.268568,0.264884,0.267008
4,Alabama,0.190949,0.220957,0.228025,0.213888,0.183750,0.156788,NaN,NaN,0.155298,0.141964,0.14533,NaN,0.134338,0.119708,NaN,NaN

In [10]:
SocSci4.drop(range(0,4), inplace = True)
SocSci4.drop(range(55,64), inplace = True)
SocSci4 = SocSci4.reset_index(drop = True)
SocSci4

,Table S-37,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
0,Alabama,0.190949,0.220957,0.228025,0.213888,0.183750,0.156788,NaN,NaN,0.155298,0.141964,0.145330,NaN,0.134338,0.119708,NaN,NaN
1,Alaska,0.388663,0.388763,0.419790,0.352101,0.321277,0.331395,0.389433,0.337608,0.399144,0.385943,0.365710,0.332338,0.323911,0.361669,0.377157,0.345757
2,Arizona,0.337961,0.342921,0.343851,0.332925,0.341767,0.336640,0.393688,0.332049,0.443660,0.302360,0.273866,0.253266,0.298407,0.277046,0.280690,0.282127
3,Arkansas,0.201128,0.233727,0.218843,0.207398,0.260070,0.275498,0.308454,0.182289,0.207955,0.172291,0.179594,0.170868,NaN,0.149414,0.157483,NaN
4,California,0.390986,0.414707,0.427468,0.421287,0.430915,0.471977,0.530668,0.327174,0.420829,0.352148,0.342451,0.342466,0.328846,0.317288,0.292123,0.296043
5,Colorado,0.41761,0.399450,0.399717,0.437674,0.432638,0.415664,0.401029,0.306346,NaN,0.306357,0.301089,0.304505,0.294515,0.304265,0.295856,NaN
6,Connecticut,0.533829,0.536311,0.523643,0.468360,0.450595,0.465894,0.493647,0.325902,0.420184,0.336291,0.314260,0.289704,0.297693,0.280865,0.264745,0.290929
7,Delaware,0.473182,0.526646,0.421506,0.702383,0.809935,0.752569,0.717454,0.251427,0.468483,0.236599,0.242636,0.230952,0.235110,0.245031,0.259775,0.274241
8,District of Columbia,2.24623,2.586221,2.927077,2.840499,2.740873,2.753737,2.641326,2.283426,2.503374,2.406082,2.502065,2.765879,2.795610,3.079530,2.905877,2.582927
9,Florida,0.27503,0.309264,0.333953,0.312230,0.271003,0.259659,0.277191,NaN,0.220647,0.196595,0.194547,0.186816,0.160499,0.154950,0.176980,0.184465
10,Georgia,0.2692,0.268400,0.292775,0.288386,0.305295,0.334786,0.372317,0.218440,0.259575,0.189227,0.183006,0.190548,NaN,0.176063,0.194259,0.216623
11,Hawaii,0.339074,0.412971,0.394085,0.445646,0.473530,0.462101,0.495058,0.489827,0.460829,0.433519,0.413484,0.448921,0.440351,0.449282,0.412329,0.386419
12,Idaho,0.282315,0.266858,0.276155,NaN,0.390990,0.324496,0.343357,0.248844,0.298618,0.312427,0.308320,0.284968,0.236502,0.232106,0.195441,0.189764
13,Illinois,0.412474,0.439256,0.432973,0.445710,0.432085,0.424659,0.423194,0.202228,0.294931,0.207420,0.207198,0.190431,0.187093,0.203089,0.213568,NaN
14,Indiana,0.205878,0.220210,0.220312,0.213168,0.216131,0.251057,0.294141,0.215792,0.269751,0.224402,0.223877,NaN,0.195428,0.198579,0.185855,NaN
15,Iowa,0.264644,0.285302,0.283433,0.319676,0.349378,0.351391,0.375222,0.199512,0.276722,0.188341,0.176321,0.159975,0.156521,0.166134,0.174541,0.177726
16,Kansas,0.377659,0.354586,0.361041,0.362555,0.381399,0.437958,0.464889,0.288171,0.344783,0.269509,0.260389,0.197867,0.198304,0.196481,0.207434,0.202853
17,Kentucky,0.227376,0.239600,0.249061,0.251709,0.266955,0.274499,0.281366,0.231344,0.248143,0.219861,0.218755,0.205751,0.204002,0.206991,0.193452,0.183081
18,Louisiana,0.196558,0.192998,0.178461,0.187958,NaN,0.163720,0.173616,0.137492,NaN,NaN,0.106083,0.116922,0.117568,0.120177,0.122499,0.140038
19,Maine,0.226447,0.245676,0.272913,0.283125,0.289990,0.311181,0.307254,0.270172,0.288375,0.277056,0.274711,0.240454,0.240060,0.231392,0.245335,0.236149
20,Maryland,0.534187,0.553430,0.575840,0.547966,0.587795,0.585197,0.597984,NaN,NaN,0.419408,0.393769,0.371064,NaN,0.391912,NaN,NaN
21,Massachusetts,0.612,0.626700,0.630617,0.658258,0.663998,0.707913,0.766485,NaN,NaN,NaN,0.465949,0.452972,NaN,0.453769,0.439617,NaN
22,Michigan,0.33245,0.302670,0.310044,0.339756,0.364798,0.416631,0.422199,0.264118,0.294594,0.239911,0.240573,0.200062,0.202576,0.199901,0.180307,0.192921
23,Minnesota,0.460698,0.520750,0.534650,0.536725,0.540975,0.517587,0.524806,0.240395,0.353311,0.227177,NaN,0.239192,NaN,0.260105,0.297012,0.322209
24,Mississippi,0.179006,0.171556,0.170495,0.187781,0.197523,0.228429,0.256179,0.220392,0.210605,NaN,0.174425,NaN,0.151823,0.129779,0.136672,0.120125
25,Missouri,0.247425,0.281074,0.331847,0.349201,0.349443,0.306915,0.297926,0.191620,0.227710,0.199546,0.169375,0.174668,0.174395,0.176587,0.168180,NaN
26,Montana,0.309002,0.376777,0.422043,0.407370,NaN,0.342273,0.372478,0.275748,0.286985,0.286785,0.282389,0.272934,0.284002,0.345252,0.327734,0.325937
27,Nebraska,0.408163,0.423805,0.434409,0.432795,0.389211,0.377106,0.426497,0.195189,0.307308,0.201130,0.226501,0.233310,0.235921,0.221074,0.236027,0.240215
28,Nevada,0.24399,0.290184,0.250076,0.278250,0.243491,0.224529,0.236469,0.170629,0.223764,0.156145,0.153650,0.145426,0.146009,0.147923,0.142724,0.144752
29,New Hampshire,0.317659,0.304055,0.328206,0.283634,0.287706,0.308871,0.327742,0.266813,0.252188,0.199115,0.206388,0.215311,0.223495,0.224789,0.241557,0.240458
30,New Jersey,0.315109,0.415532,0.452607,NaN,0.436926,0.383061,0.376808,0.202623,0.248724,0.206921,0.224021,0.235704,0.239582,0.247766,0.231817,0.218262
31,New Mexico,0.376146,0.468880,0.468936,0.423128,0.439497,0.517401,0.489761,0.492566,0.342061,0.325640,0.312508,0.326142,0.347053,0.326530,0.367005,0.356052
32,New York,0.457857,0.501210,0.529432,0.549969,0.550613,0.574269,0.591020,0.346955,0.442714,0.384909,0.406466,NaN,0.391658,0.400323,0.389341,0.395179
33,North Carolina,0.334128,0.346090,0.355934,0.367357,0.349823,0.384159,0.427536,0.281755,0.338938,0.273538,0.276410,0.269420,0.276117,0.276765,0.278011,0.269209
34,North Dakota,0.238383,0.228092,0.237428,0.274022,0.216393,0.208357,0.217742,0.146187,0.182978,0.166134,0.170241,0.172563,0.169711,0.190499,0.201598,0.187252
35,Ohio,0.308198,0.317201,NaN,0.306490,0.321828,0.343971,0.356281,0.214154,0.259948,0.213682,0.208356,0.197082,NaN,0.187153,0.201652,0.211748
36,Oklahoma,0.368478,0.320250,0.320068,0.347206,0.332921,0.332531,0.306163,0.205559,0.351741,0.316361,0.330370,0.173077,0.171558,0.169514,0.200890,0.198197
37,Oregon,0.357189,0.352593,0.332754,0.366354,0.396516,0.378499,0.403819,0.320443,0.383835,0.337288,0.335305,0.295818,0.283538,0.257965,0.267644,0.266689
38,Pennsylvania,0.342347,0.386811,0.429317,NaN,0.468827,0.490783,NaN,0.309307,0.404380,0.340571,0.352513,0.352858,0.328226,0.301896,0.270167,0.256512
39,Rhode Island,0.423196,0.381020,0.343886,0.358512,0.362237,0.361607,0.361845,0.294544,0.368087,0.379674,0.361763,0.331947,0.322519,0.321976,0.342502,0.358899
40,South Carolina,0.257912,0.217053,0.206353,0.217369,0.230038,0.255192,0.278995,0.204371,0.231826,0.202054,0.197139,0.176394,0.161814,0.168702,0.169697,0.156623
41,South Dakota,0.227416,0.258753,0.307898,0.291163,0.282486,0.267704,0.279977,0.263165,0.257213,NaN,0.235738,0.246793,0.271016,0.261065,0.236012,0.239161
42,Tennessee,0.204985,0.205624,0.191694,0.227707,0.250070,0.262719,0.249130,0.165018,0.200206,0.176120,0.180367,0.184399,0.187973,0.165915,0.166338,0.182961
43,Texas,0.275499,0.300969,0.310361,0.333164,0.347554,0.343071,0.346090,0.204264,0.250670,0.190748,0.196171,0.194052,0.193043,0.191652,0.190734,0.195975
44,Utah,0.410158,0.440026,0.419384,0.450904,0.383027,0.370635,0.355044,0.269913,0.266728,0.248158,0.255092,0.282667,0.286154,0.277111,0.279300,0.268561
45,Vermont,0.5628,0.577196,0.638334,0.687560,0.710633,0.670807,0.683395,0.418133,0.526081,0.445442,0.442522,0.491613,0.523802,0.525158,0.458851,0.429213
46,Virginia,0.492956,0.542033,0.579267,0.622154,0.598848,0.582133,0.574450,0.343034,0.419040,0.351672,0.370376,0.383172,0.401092,0.417492,0.427187,NaN
47,Washington,0.563239,0.627620,0.623747,0.644888,0.626667,0.628462,0.660293,0.343084,0.417178,0.317285,NaN,NaN,0.305972,0.301261,0.300005,0.287191
48,West Virginia,0.332255,0.294440,0.293953,0.296949,0.276208,0.312091,0.308103,0.279001,0.308461,0.344808,0.377768,0.371616,0.387553,0.299667,0.281760,0.275617
49,Wisconsin,0.384014,0.374544,0.390477,0.366590,0.355385,0.339613,0.355800,0.223480,0.264632,0.216588,0.224413,0.244514,0.211791,0.209981,0.203174,0.251004
50,Wyoming,0.290782,0.336482,0.329902,0.343171,0.344108,0.359180,NaN,0.285280,0.341197,0.266149,NaN,0.279458,0.285382,0.267999,0.276140,0.282192

In [11]:
m = SocSci4.mean(axis=1)
for i, col in enumerate(SocSci4):
    SocSci4.iloc[:, i] = SocSci4.iloc[:, i].fillna(m)
SocSci4 = SocSci4.drop(['Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
                          'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45',
                          'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49'], axis = 1)

SocSci4 = SocSci4.rename(columns = {'Table S-37':'State',
                                       'Unnamed: 50':'Social Scientists 2018 (Percent)'})

SocSci4.head(10)

                  State  Social Scientists 2018 (Percent)
0               Alabama                          0.170005
1                Alaska                          0.345757
2               Arizona                          0.282127
3              Arkansas                          0.209530
4            California                          0.296043
5              Colorado                          0.353777
6           Connecticut                          0.290929
7              Delaware                          0.274241
8  District of Columbia                          2.582927
9               Florida                          0.184465

In [12]:
SocSciDF = [SocSci2, SocSci3, SocSci4]

SocSciFinal = reduce(lambda left, right: pd.merge(left, right, on = 'State', how = 'outer'), SocSciDF)

SocSciFinal

,State,Social Scientists 2018,All Occupations 2018,Social Scientists 2018 (Percent)
0,Alabama,3195.000000,1943760.0,0.170005
1,Alaska,1090.000000,315250.0,0.345757
2,Arizona,7870.000000,2789520.0,0.282127
3,Arkansas,2426.923077,1210120.0,0.209530
4,California,50350.000000,17007690.0,0.296043
5,Colorado,8079.230769,2620640.0,0.353777
6,Connecticut,4830.000000,1660200.0,0.290929
7,Delaware,1230.000000,448510.0,0.274241
8,District of Columbia,18400.000000,712370.0,2.582927
9,Florida,15880.000000,8608660.0,0.184465
10,Georgia,9520.000000,4394740.0,0.216623
11,Hawaii,2480.000000,641790.0,0.386419
12,Idaho,1340.000000,706140.0,0.189764
13,Illinois,17755.714286,5991270.0,0.307417
14,Indiana,6471.538462,3048100.0,0.225285
15,Iowa,2740.000000,1541700.0,0.177726
16,Kansas,2790.000000,1375380.0,0.202853
17,Kentucky,3460.000000,1889870.0,0.183081
18,Louisiana,2680.000000,1913770.0,0.140038
19,Maine,1430.000000,605550.0,0.236149
20,Maryland,12727.000000,2684010.0,0.502437
21,Massachusetts,19024.000000,3571360.0,0.586628
22,Michigan,8330.000000,4317830.0,0.192921
23,Minnesota,9240.000000,2867700.0,0.322209
24,Mississippi,1350.000000,1123830.0,0.120125
25,Missouri,6507.857143,2804780.0,0.242749
26,Montana,1510.000000,463280.0,0.325937
27,Nebraska,2350.000000,978290.0,0.240215
28,Nevada,1950.000000,1347130.0,0.144752
29,New Hampshire,1570.000000,652920.0,0.240458
30,New Jersey,8840.000000,4050170.0,0.218262
31,New Mexico,2890.000000,811680.0,0.356052
32,New York,37090.000000,9385620.0,0.395179
33,North Carolina,11800.000000,4383210.0,0.269209
34,North Dakota,780.000000,416550.0,0.187252
35,Ohio,11470.000000,5416810.0,0.211748
36,Oklahoma,3160.000000,1594370.0,0.198197
37,Oregon,5030.000000,1886090.0,0.266689
38,Pennsylvania,15000.000000,5847690.0,0.256512
39,Rhode Island,1730.000000,482030.0,0.358899
40,South Carolina,3230.000000,2062280.0,0.156623
41,South Dakota,1010.000000,422310.0,0.239161
42,Tennessee,5410.000000,2956920.0,0.182961
43,Texas,23740.000000,12113810.0,0.195975
44,Utah,3910.000000,1455910.0,0.268561
45,Vermont,1310.000000,305210.0,0.429213
46,Virginia,17101.428571,3832840.0,0.472282
47,Washington,9360.000000,3259150.0,0.287191
48,West Virginia,1920.000000,696620.0,0.275617
49,Wisconsin,7150.000000,2848560.0,0.251004
50,Wyoming,760.000000,269320.0,0.282192

In [13]:
COVIDCases = pd.read_csv('us-states.csv')
COVIDCases = COVIDCases.groupby(['state']).sum()
COVIDCases = COVIDCases.reset_index()
COVIDCases.drop([11, 36, 41, 49], inplace = True)
COVIDCases = COVIDCases.reset_index(drop = True)
COVIDCases.state

0                  Alabama
1                   Alaska
2                  Arizona
3                 Arkansas
4               California
5                 Colorado
6              Connecticut
7                 Delaware
8     District of Columbia
9                  Florida
10                 Georgia
11                  Hawaii
12                   Idaho
13                Illinois
14                 Indiana
15                    Iowa
16                  Kansas
17                Kentucky
18               Louisiana
19                   Maine
20                Maryland
21           Massachusetts
22                Michigan
23               Minnesota
24             Mississippi
25                Missouri
26                 Montana
27                Nebraska
28                  Nevada
29           New Hampshire
30              New Jersey
31              New Mexico
32                New York
33          North Carolina
34            North Dakota
35                    Ohio
36                Oklahoma
37                  Oregon
38            Pennsylvania
39            Rhode Island
40          South Carolina
41            South Dakota
42               Tennessee
43                   Texas
44                    Utah
45                 Vermont
46                Virginia
47              Washington
48           West Virginia
49               Wisconsin
50                 Wyoming
Name: state, dtype: object

In [14]:
COVIDCases = COVIDCases.rename(columns = {'state':'State'})
COVIDCases.head()

        State  fips    cases  deaths
0     Alabama    73   387786   14345
1      Alaska   148    18316     367
2     Arizona   480   426614   18857
3    Arkansas   375   161569    3301
4  California   726  2664110  102387

In [15]:
COVIDSocSci = pd.merge(COVIDCases, SocSciFinal, how = 'left', on = 'State')
COVIDSocSci

,State,fips,cases,deaths,Social Scientists 2018,All Occupations 2018,Social Scientists 2018 (Percent)
0,Alabama,73,387786,14345,3195.000000,1943760.0,0.170005
1,Alaska,148,18316,367,1090.000000,315250.0,0.345757
2,Arizona,480,426614,18857,7870.000000,2789520.0,0.282127
3,Arkansas,375,161569,3301,2426.923077,1210120.0,0.209530
4,California,726,2664110,102387,50350.000000,17007690.0,0.296043
5,Colorado,648,766512,37828,8079.230769,2620640.0,0.353777
6,Connecticut,702,1314995,104185,4830.000000,1660200.0,0.290929
7,Delaware,750,234327,7813,1230.000000,448510.0,0.274241
8,District of Columbia,869,229466,10822,18400.000000,712370.0,2.582927
9,Florida,1020,1726811,63147,15880.000000,8608660.0,0.184465
10,Georgia,1092,1282091,54209,9520.000000,4394740.0,0.216623
11,Hawaii,1200,31433,681,2480.000000,641790.0,0.386419
12,Idaho,1168,103987,2828,1340.000000,706140.0,0.189764
13,Illinois,2074,2843621,122000,17755.714286,5991270.0,0.307417
14,Indiana,1440,920434,53042,6471.538462,3048100.0,0.225285
15,Iowa,1482,396980,9203,2740.000000,1541700.0,0.177726
16,Kansas,1580,231885,6527,2790.000000,1375380.0,0.202853
17,Kentucky,1680,246480,11851,3460.000000,1889870.0,0.183081
18,Louisiana,1694,1443404,90609,2680.000000,1913770.0,0.140038
19,Maine,1702,61284,2451,1430.000000,605550.0,0.236149
20,Maryland,1944,1173802,56126,12727.000000,2684010.0,0.502437
21,Massachusetts,2850,2929874,167711,19024.000000,3571360.0,0.586628
22,Michigan,1976,2023047,171867,8330.000000,4317830.0,0.192921
23,Minnesota,2160,377850,18934,9240.000000,2867700.0,0.322209
24,Mississippi,2100,358459,15047,1350.000000,1123830.0,0.120125
25,Missouri,2291,395952,17924,6507.857143,2804780.0,0.242749
26,Montana,2190,23875,676,1510.000000,463280.0,0.325937
27,Nebraska,3038,259429,3535,2350.000000,978290.0,0.240215
28,Nevada,2592,259808,11975,1950.000000,1347130.0,0.144752
29,New Hampshire,2772,117245,4507,1570.000000,652920.0,0.240458
30,New Jersey,2788,5645458,332869,8840.000000,4050170.0,0.218262
31,New Mexico,2625,177827,6867,2890.000000,811680.0,0.356052
32,New York,3060,15041806,1081194,37090.000000,9385620.0,0.395179
33,North Carolina,3071,568719,19258,11800.000000,4383210.0,0.269209
34,North Dakota,2850,55932,1219,780.000000,416550.0,0.187252
35,Ohio,3003,908834,47879,11470.000000,5416810.0,0.211748
36,Oklahoma,3200,187462,10394,3160.000000,1594370.0,0.198197
37,Oregon,3567,134979,5067,5030.000000,1886090.0,0.266689
38,Pennsylvania,3360,2320771,127278,15000.000000,5847690.0,0.256512
39,Rhode Island,3740,401931,14251,1730.000000,482030.0,0.358899
40,South Carolina,3600,313173,11859,3230.000000,2062280.0,0.156623
41,South Dakota,3496,122292,1121,1010.000000,422310.0,0.239161
42,Tennessee,3807,583792,10198,5410.000000,2956920.0,0.182961
43,Texas,4944,1553075,41267,23740.000000,12113810.0,0.195975
44,Utah,4410,245859,2472,3910.000000,1455910.0,0.268561
45,Vermont,3950,45230,2320,1310.000000,305210.0,0.429213
46,Virginia,4029,866807,28754,17101.428571,3832840.0,0.472282
47,Washington,6625,807848,42371,9360.000000,3259150.0,0.287191
48,West Virginia,3726,56158,1950,1920.000000,696620.0,0.275617
49,Wisconsin,6050,393823,15587,7150.000000,2848560.0,0.251004
50,Wyoming,4200,28407,281,760.000000,269320.0,0.282192

In [16]:
COVIDSocSci = COVIDSocSci.drop(['fips'], axis = 1)
COVIDSocSci

,State,cases,deaths,Social Scientists 2018,All Occupations 2018,Social Scientists 2018 (Percent)
0,Alabama,387786,14345,3195.000000,1943760.0,0.170005
1,Alaska,18316,367,1090.000000,315250.0,0.345757
2,Arizona,426614,18857,7870.000000,2789520.0,0.282127
3,Arkansas,161569,3301,2426.923077,1210120.0,0.209530
4,California,2664110,102387,50350.000000,17007690.0,0.296043
5,Colorado,766512,37828,8079.230769,2620640.0,0.353777
6,Connecticut,1314995,104185,4830.000000,1660200.0,0.290929
7,Delaware,234327,7813,1230.000000,448510.0,0.274241
8,District of Columbia,229466,10822,18400.000000,712370.0,2.582927
9,Florida,1726811,63147,15880.000000,8608660.0,0.184465
10,Georgia,1282091,54209,9520.000000,4394740.0,0.216623
11,Hawaii,31433,681,2480.000000,641790.0,0.386419
12,Idaho,103987,2828,1340.000000,706140.0,0.189764
13,Illinois,2843621,122000,17755.714286,5991270.0,0.307417
14,Indiana,920434,53042,6471.538462,3048100.0,0.225285
15,Iowa,396980,9203,2740.000000,1541700.0,0.177726
16,Kansas,231885,6527,2790.000000,1375380.0,0.202853
17,Kentucky,246480,11851,3460.000000,1889870.0,0.183081
18,Louisiana,1443404,90609,2680.000000,1913770.0,0.140038
19,Maine,61284,2451,1430.000000,605550.0,0.236149
20,Maryland,1173802,56126,12727.000000,2684010.0,0.502437
21,Massachusetts,2929874,167711,19024.000000,3571360.0,0.586628
22,Michigan,2023047,171867,8330.000000,4317830.0,0.192921
23,Minnesota,377850,18934,9240.000000,2867700.0,0.322209
24,Mississippi,358459,15047,1350.000000,1123830.0,0.120125
25,Missouri,395952,17924,6507.857143,2804780.0,0.242749
26,Montana,23875,676,1510.000000,463280.0,0.325937
27,Nebraska,259429,3535,2350.000000,978290.0,0.240215
28,Nevada,259808,11975,1950.000000,1347130.0,0.144752
29,New Hampshire,117245,4507,1570.000000,652920.0,0.240458
30,New Jersey,5645458,332869,8840.000000,4050170.0,0.218262
31,New Mexico,177827,6867,2890.000000,811680.0,0.356052
32,New York,15041806,1081194,37090.000000,9385620.0,0.395179
33,North Carolina,568719,19258,11800.000000,4383210.0,0.269209
34,North Dakota,55932,1219,780.000000,416550.0,0.187252
35,Ohio,908834,47879,11470.000000,5416810.0,0.211748
36,Oklahoma,187462,10394,3160.000000,1594370.0,0.198197
37,Oregon,134979,5067,5030.000000,1886090.0,0.266689
38,Pennsylvania,2320771,127278,15000.000000,5847690.0,0.256512
39,Rhode Island,401931,14251,1730.000000,482030.0,0.358899
40,South Carolina,313173,11859,3230.000000,2062280.0,0.156623
41,South Dakota,122292,1121,1010.000000,422310.0,0.239161
42,Tennessee,583792,10198,5410.000000,2956920.0,0.182961
43,Texas,1553075,41267,23740.000000,12113810.0,0.195975
44,Utah,245859,2472,3910.000000,1455910.0,0.268561
45,Vermont,45230,2320,1310.000000,305210.0,0.429213
46,Virginia,866807,28754,17101.428571,3832840.0,0.472282
47,Washington,807848,42371,9360.000000,3259150.0,0.287191
48,West Virginia,56158,1950,1920.000000,696620.0,0.275617
49,Wisconsin,393823,15587,7150.000000,2848560.0,0.251004
50,Wyoming,28407,281,760.000000,269320.0,0.282192

In [17]:
COVIDSocSci.to_csv('SocSci_jobs.csv')